### DISCUSSION TITLE
What determines the renaming of the file?

### DISCUSSION THREAD

**Discussion by sheldonhull** [aquaproj/aqua#1267] [Deprecated (Question and Answer)] [answered]
When I have an asset that isn't named the same as the repo, what property for a custom github release is setting the final binary name?

I tried files but that wasn't successful.

I'm _loving_ this tool!

**Comment by suzuki-shunsuke** [comment, marked as answer]
For example, `cli/cli`'s command name is `gh`. In this case you configure `files` as the following.

https://github.com/aquaproj/aqua-registry/blob/68e6e250f696806b76d9d80a274f7cd9d0d9e745/pkgs/cli/cli/registry.yaml#L14-L16

```yaml
    files:
      - name: gh
        src: gh_{{trimV .Version}}_{{.OS}}_{{.Arch}}/bin/gh
```

> I tried files but that wasn't successful.

Could you tell us the detail such as the command and output?
