### DISCUSSION TITLE
Provide a tag attribute for a package and allow this to filter the packages installed in CI or other environments

### DISCUSSION THREAD

**Discussion by sheldonhull** [aquaproj/aqua#1330] [Deprecated (Feature Request)] [answered]
I'd like to keep a single config for `aqua.yaml`, but I'd prefer to have certain tools only installed when needed in a CI context. Even better, I'd like to specify something like:

```yaml
---
packages:
- name: dbrgn/tealdeer@v9.9.9
  tags: ['developer']
- name: goreleaser/goreleaser@v9.9.9
  tags: ['developer', 'release']
- name: gotestsum/gotestsum@v9.9.9
  tags: ['developer', 'test']
```

Then on installation all my installation scripts could optionally add `aqua install --tags 'release,test'` for github actions.

## Compatibility

The thing I like about this approach is that it would be zero impact to existing processes using aqua. It's an opt-in feature. It also doesn't require duplication of the config file which could double aqua updates through renovate if similar packages are required for different types of tasks.

## Lazy Install Is Great But Not What I Need for CI

Lazy install is an amazing concept, and I use it now on my personal codespace setup scripts. The catch is that there's a few places where that can break down, let's say stderr or stdout gets mixed up with aqua installation stuff from the proxy, then a tool like vscode, or another cli tool might error out. It's too much to troubleshoot. 

I would much rather just "install" and cache at the beginning of a github action, than rely fully on the aqua proxy. It reduces my long-term worry about adopting aqua as I could just replace it with another install method. Using the proxy could result in more refactoring work with github actions if I leverage it more.

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback and proposal.
This is similar to https://github.com/aquaproj/aqua/issues/441 (https://github.com/aquaproj/aqua/pull/437#issuecomment-987903392 , https://github.com/aquaproj/aqua/pull/437#issuecomment-987260859 ).

I'd like to keep `aqua.yaml` simple, so I didn't implement the feature.
But I'd like to reconsider, because I understand that Lazy Install doesn't meet some usecase.
`tags` seems to be good, but I'm not sure if this is the best.

As for Lazy Install Log, you can suppress the log by setting `AQUA_LOG_LEVEL` to `error` as a workaround.

**Reply by sheldonhull** [reply]
The thing is aqua, solves, more than a developer needing to install tools it cuts duplication by allowing aqua to help with go, goreleaser and other tools. It's a great way to simplify, just runs into a few issues with that flexibility. 

Great work on this!

**Comment by suzuki-shunsuke** [comment]
# Specification

Add the filed `tags` to `aqua.yaml`'s package.

e.g.

```yaml
registries:
- type: standard
  ref: v3.79.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: suzuki-shunsuke/tfcmt@v3.2.0
  tags:
    - ci
    - foo
- name: cli/cli@v2.0.0
- name: suzuki-shunsuke/github-comment@v5.0.0
  tags:
    - test
```

The field affects only the following commands.

- [x] install
- [x] cp
- [ ] exec
- [ ] init
- [ ] generate
- [ ] which
- [ ] list
- [ ] generate-registry
- [ ] completion
- [ ] update-checksum

The following options are added.

- `--tag (-t)` (e.g. `-t ci -t test`)
- `--ignore-tags` (boolean)

Packages with `tags` are installed only when any tags are specified by `-t` option.

When `aqua i`'s `-l` options is set, package's `tags` fields are ignored.

## Example

aqua.yaml

```yaml
registries:
- type: standard
  ref: v3.79.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: suzuki-shunsuke/tfcmt@v3.2.0
  tags:
    - ci
    - foo
- name: cli/cli@v2.0.0
- name: suzuki-shunsuke/github-comment@v5.0.0
  tags:
    - test
```

```console
$ aqua i # Install only cli/cli
$ aqua i -l # Create links for all packages
$ aqua i -t ci  # Install only suzuki-shunsuke/tfcmt
$ aqua i --ignore-tags # Install all packages
```

**Reply by suzuki-shunsuke** [reply]
Hmm...The behaviour isn't obvious.
I would like to keep aqua simple.

Currently, users only have to run `aqua i [-l]`. It's consistent and very simple.

**Reply by suzuki-shunsuke** [reply]
Let's create symbolic all packages even if `tags` are specified.
Then we can assure that the executed tool version is correct.

**Reply by suzuki-shunsuke** [reply]
```yaml
registries:
- type: standard
  ref: v3.79.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: suzuki-shunsuke/tfcmt@v3.2.0
  tags:
    - ci
    - foo
- name: cli/cli@v2.0.0
- name: suzuki-shunsuke/github-comment@v5.0.0
  tags:
    - test
```

```console
$ aqua i -t ci
```

In the above case, should `cli/cli` be installed?

**Reply by suzuki-shunsuke** [reply]
> In the above case, should cli/cli be installed?

I think `No`.

```console
$ aqua i # Install packages that have no tag
$ aqua i -t ci # Install packages that have the tag `ci`
$ aqua i -t ci -t dev # Install packages that have either `ci` or `dev` tag
$ aqua i --ignore-tags # Install all packages
```

This is clear and simple.

**Reply by suzuki-shunsuke** [reply]
- https://github.com/aquaproj/aqua/issues/441#issuecomment-1288076366

**Reply by sheldonhull** [reply]
This is great!

- Generate should support tags even if not interactively. That way I can specify a new ci package. 
- Anytime I specifically pass tag I only want those installed, even if linking. It's opt in for this feature so it seems reasonable. Installing other apps even if lazy installed I think has behavior because I wouldn't expect. 

I'm exited to see where this goes. 🎉🎉

**Reply by suzuki-shunsuke** [reply]
Thank you for your feedback.

> Generate should support tags even if not interactively. That way I can specify a new ci package.

`Generate` means `aqua generate (aqua g)` command, right?
Do you expect the following usage?

```console
$ aqua g cli/cli --tags ci
- name: cli/cli@v2.18.1
  tags:
  - ci
```

If so, I think this isn't necessarily needed, because you can add tags with your editor easily.

> Anytime I specifically pass tag I only want those installed, even if linking.
> It's opt in for this feature so it seems reasonable.
> Installing other apps even if lazy installed I think has behavior because I wouldn't expect.

You disagree the following specification, right?

> Note that symbolic links of all packages are created regardless tags, so that you can execute all tools by Lazy Install and assure that tools are managed by aqua.

Let me explain about the specification.
Please see the following `aqua.yaml`.

```yaml
registries:
- type: standard
  ref: v3.79.0
packages:
- name: cli/cli@v2.0.0
  tags:
  - ci
```

When this file is used in the project, I think GitHub CLI should be managed by aqua in the project.
But if the symbolic link for GitHub CLI isn't created, GitHub CLI installed by other than aqua (e.g. Homebrew) would be executed.
I think it's undesirable, so I'd like to create symbolic links as much as possible.
