### DISCUSSION TITLE
Support a new package type `s3`

### DISCUSSION THREAD

**Discussion by suzuki-shunsuke** [aquaproj/aqua#1953] [Deprecated (Feature Request)]
### Feature Overview

Support a new package type `s3`.

### Why is the feature needed?

To install private tools from S3.

- https://github.com/aquaproj/aqua/issues/1929#issuecomment-1534453355

:warning: Note that the object URI must conform to semver.

### Does the feature include Breaking Changes?

No.

### Example Code

registry.yaml

```yaml
packages:
  - name: mytools/yoo
    type: s3
    bucket: mybucket
    path: mytools/yoo-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
    format: tar.gz
```

#### Authentication

Authenticate with AWS SDK for Go.

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config

### Reference

- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/cp.html
