### DISCUSSION TITLE
How am I supposed to pass multiple policy files to update checksums against?

### DISCUSSION THREAD

**Discussion by sheldonhull** [aquaproj/aqua#2007] [Deprecated (Question and Answer)] [answered]
### Question

I have a repo containing both the project level `.aqua` configuration, and also my global configuration that I deploy via `chezmoi`.

![CleanShot 2023-05-16 at 19 18 30](https://github.com/aquaproj/aqua/assets/3526320/4259f701-0b37-4cf2-9d81-e8b4fbdbf576)

### Background of the question

- Am i supposed to be able to pass both policies, or would I need to invoke 2x for each?
- Also, is it important for me to pass the paths for the files for all commands related to policy and checksum, or will the checksum command find all the `.aqua` files without me needing to specify that it's in the `.aqua` directory (all my projects have moved to this as it's much cleaner).

### Example Code

```yaml
---
name: update-aqua-checksum
on:
  pull_request:
    paths:
      - aqua.yaml
      - aqua-checksums.json
      - .aqua/aqua.yaml
      - .aqua/aqua-checksums.json
      - private_dot_config/exact_aqua/aqua.yaml
      - private_dot_config/exact_aqua/aqua-checksums.json
jobs:
  update-aqua-checksums:
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@7a77a05ec15945a7360f871e7751547acfae4f41 # renovate: tag=v0.1.6
    permissions:
      contents: write
    with:
      aqua_policy_config: '.aqua/aqua-policy.yaml:private_dot_config/exact_aqua/aqua-policy.yaml'
      aqua_version: v2.6.0
      prune: true
      policy_allow: '.aqua/aqua-policy.yaml:private_dot_config/exact_aqua/aqua-policy.yaml'
    secrets:
      gh_token: '${{secrets.GITHUB_TOKEN}}'

```

**Comment by suzuki-shunsuke** [comment, marked as answer]
The input `policy_allow` doesn't support multiple files at the moment.
And you don't have to specify the same file in both `aqua_policy_config` and `policy_allow`.

Please try the following code.

```yaml
      aqua_policy_config: 'private_dot_config/exact_aqua/aqua-policy.yaml'
      policy_allow: 'true'
```

```yaml
  update-aqua-checksums:
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@7a77a05ec15945a7360f871e7751547acfae4f41 # renovate: tag=v0.1.6
    permissions:
      contents: write
    with:
      aqua_policy_config: 'private_dot_config/exact_aqua/aqua-policy.yaml'
      aqua_version: v2.6.0
      prune: true
      policy_allow: 'true'
    secrets:
      gh_token: '${{secrets.GITHUB_TOKEN}}'
```
