### DISCUSSION TITLE
Install packages by `cargo` or `go_install` if the asset for the platform isn't released in GitHub Releases

### DISCUSSION THREAD

**Discussion by suzuki-shunsuke** [aquaproj/aqua#2026] [Deprecated (Feature Request)] [answered]
### Feature Overview

Install packages by `cargo` or `go_install` if the asset for the platform isn't released in GitHub Releases.

### Why is the feature needed?

To support platforms where a tool doesn't provide assets.

For example, some `github_release` packages don't support `linux/arm64` and `windows`.

Of course we can achieve this using `overrides`.

e.g. https://github.com/aquaproj/aqua-registry/blob/8d552f251ded112b42e681279d71b0af59fce85f/pkgs/slsa-framework/slsa-verifier/registry.yaml#L11-L19

```yaml
        type: go_install
        path: github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier
        asset: slsa-verifier
        overrides:
          - goos: linux
            goarch: amd64
            type: github_release
            asset: slsa-verifier-{{.OS}}-{{.Arch}}
            format: raw
```

But I'd like to provide the simple way to achieve this.

### Does the feature include Breaking Changes?

No.

### Example Code

registry.yaml

```yaml
        type: github_release
        asset: slsa-verifier-{{.OS}}-{{.Arch}}
        format: raw
        supported_envs:
          - linux/amd64
        go_path: github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier # New!
```

If the platform isn't contained in `supported_envs` and `go_path` is set, the package is installed by `go_install`.

### Reference

- https://twitter.com/wbelucky/status/1661279221874819073
