### DISCUSSION TITLE
Add description and homepage fields to packages in aqua.yaml

### DISCUSSION THREAD

**Discussion by dudicoco** [aquaproj/aqua#2027] [Deprecated (Feature Request)] [answered]
### Feature Overview

When running `aqua g` and selecting a package the output could include the `description` and `homepage` fields from the package `registry.yaml`.

This is similar to what `brew bundle dump --describe` does:

```sh
# Official Amazon AWS command-line interface
brew "awscli"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
```

### Why is the feature needed?

It would be helpful to have additional information about the packages within the aqua.yaml config file and a clickable link to their homepages.

### Does the feature include Breaking Changes?

Not to my knowledge.

### Example Code

The new fields could be added by default, if a new flag is needed then perhaps `--description`.

```console
$ aqua g --description cli/cli
```

```yaml
- name: cli/cli@v2.29.0
  description: GitHub’s official command line tool
  homepage: https://github.com/cli/cli
```
