### DISCUSSION TITLE
Support installing packages by `go build`

### DISCUSSION THREAD

**Discussion by suzuki-shunsuke** [aquaproj/aqua#2039] [Deprecated (Feature Request)] [answered]
### Feature Overview

Support installing packages by `go build`.

### Why is the feature needed?

Because some packages couldn't be installed by `go install` but could be installed by `go build`.

aqua ever supported `go` type package, but it was abandoned at aqua v2 because we thought we could replace it to `go_install` type package.

- https://aquaproj.github.io/docs/reference/registry-config/go-package
- https://aquaproj.github.io/docs/reference/upgrade-guide/v2/remove-type-go

But we found that some packages couldn't be installed by `go install` but could be installed by `go build`.

For example, suzuki-shunsuke/github-comment v5 can't be installed by `go install`.

```console
$ go install github.com/suzuki-shunsuke/github-comment/v5/cmd/github-comment@v5.2.1
go: github.com/suzuki-shunsuke/github-comment/v5/cmd/github-comment@v5.2.1: github.com/suzuki-shunsuke/github-comment@v5.2.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/suzuki-shunsuke/github-comment/v5")

$ go install github.com/suzuki-shunsuke/github-comment/cmd/github-comment@v5.2.1 
go: github.com/suzuki-shunsuke/github-comment/cmd/github-comment@v5.2.1: github.com/suzuki-shunsuke/github-comment@v5.2.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/suzuki-shunsuke/github-comment/v5")
```

This is because github-comment's go.mod was wrong.

https://github.com/suzuki-shunsuke/github-comment/blob/e5fd429b4d1bd84e8b825a2c7b693d6ac570022f/go.mod#L1

```
module github.com/suzuki-shunsuke/github-comment
```

This issue was solved by github-comment v6, but github-comment v2 ~ v5 can't still be installed by `go install`.

- https://github.com/suzuki-shunsuke/github-comment/pull/900

There are many Go tools that can't be installed by `go install`.

### Does the feature include Breaking Changes?

No.

### Example Code

There are two options.

- Recover `go` type package
- Improve `go_install` type package to support `go build`

### Reference

- https://aquaproj.github.io/docs/reference/registry-config/go-package
- https://aquaproj.github.io/docs/reference/upgrade-guide/v2/remove-type-go

**Comment by suzuki-shunsuke** [comment]
# Example

```yaml
packages:
  - type: github_release
    repo_owner: suzuki-shunsuke
    repo_name: github-comment
    asset: github-comment_{{trimV .Version}}_{{.OS}}_{{.Arch}}.tar.gz
    version_constraint: semver(">= 6.0.0")
    go_path: github.com/suzuki-shunsuke/github-comment/{{.Major}}/cmd/github-comment
    version_overrides:
      - version_constraint: semver("< 6.0.0")
        go_build:
          files:
            - name: github-comment
              src: ./cmd/github-comment
              dir: github-comment-{{trimV .Version}}
```
