### DISCUSSION TITLE
Policy is blocking a `go_install` and I can't get it past the `aqua policy allow` command

### DISCUSSION THREAD

**Discussion by sheldonhull** [aquaproj/aqua#2389] [Deprecated (Support Request)]
### aqua info

```console

$ aqua info

{
  "version": "2.16.0",
  "commit_hash": "70f84d66ba9af98008360fd7b846094f020b4c6f",
  "os": "darwin",
  "arch": "arm64",
  "pwd": "/Users/(USER)/.config/aqua",
  "root_dir": "/Users/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "AQUA_DISABLE_POLICY": "true",
    "AQUA_GITHUB_TOKEN": "(masked)",
    "AQUA_GLOBAL_CONFIG": "/Users/(USER)/.config/aqua/aqua.yaml",
    "AQUA_LOG_LEVEL": "error",
    "AQUA_POLICY_CONFIG": "/Users/(USER)/.config/aqua/aqua-policy.yaml",
    "AQUA_PROGRESS_BAR": "true"
  },
  "config_files": [
    {
      "path": "/Users/(USER)/.config/aqua/aqua.yaml"
    },
    {
      "path": "/Users/(USER)/.config/aqua/aqua.yaml"
    }
  ]
}

```

#### aqua < v2.10.0

```console
$ aqua -v
aqua version 2.16.0 (70f84d66ba9af98008360fd7b846094f020b4c6f)
```

OS (Windows, Linux, macOS, etc): `Darwin`
CPU Architecture (amd64, arm64, etc): `arm64`

### Overview

I've run the following commands (and done this directly in the global aqua directory).

```shell
pushd "${HOME}/.local/share/chezmoi/private_dot_config/exact_aqua" || (echo '❌ can not find target directory' && return)
token=$(gh auth token)
export AQUA_GITHUB_TOKEN="${token}"
echo "⚙️ aqua update-aqua"
aqua update-aqua
echo "⚙️ aqua update"
aqua update
echo "⚙️ aqua update-checksum"
aqua update-checksum
echo "aqua policy allow"
aqua policy allow "${XDG_CONFIG_HOME:-${HOME}/.config/}/aqua/aqua-policy.yaml"
echo "chezmoi apply"
chezmoi apply --keep-going
```

> IMPORTANT: `export AQUA_DISABLE_POLICY=true` is set!

I disabled policy check a while back due to a blocker and not it doesn't seem to honor the setting. Ideally I want to use it, but now it's not honoring this check either so it finally brought it back to my attention. I just ran an update and got rid of the brew managed version so I think it's showing up for me as I wasn't updated.

I just cleared out my settings and this is all that shows up for AQUA in the environment variables.

```console
$ env | grep AQUA

AQUA_DISABLE_POLICY=true
AQUA_GLOBAL_CONFIG=/Users/(USER)/.config/aqua/aqua.yaml
AQUA_PROGRESS_BAR=true
AQUA_LOG_LEVEL=error
```

### How to reproduce

```yaml
# aqua-policy.yaml
registries:
  - name: local
    type: local
    path: registry.yaml
  - type: standard
    ref: semver(">= 3.0.0")
packages:
  - registry: local # allow all packages in the Registry
  - registry: standard
  
```

```yaml
#registry.yaml

---
packages:
  - type: go_install
    name: mage-select
    path: github.com/iwittkau/mage-select
    description: CLI frontend for mage based on promptui.
    search_words:
      - mage
      - module
      - go
```

```yaml
# aqua.yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: false
registries:
  - type: standard
    ref: v4.74.0 # renovate: depName=aquaproj/aqua-registry
  - name: local
    type: local
    path: registry.yaml
packages:
  - name: mage-select
    version: v1.4.0
    registry: local
````

### Expected behaviour

I thought running the aqua policy against it would work.

### Actual behaviour

Blocks this and other packages from my local registry. Most of these are `go_install` type packages. However, I have one `github_release` type and it also fails. 

### Important Factoids

I can't remember what caused this in the past as I ran into it again. Kinda stuck on those tools. Not sure why i can't get those allowed. Disabling policy globally temporarily solves this blocker.

**Comment by suzuki-shunsuke** [comment]
Let me confirm your situation.

- aqua.yaml is at `${HOME}/.local/share/chezmoi/private_dot_config/exact_aqua/aqua.yaml`
- a policy file is at `${XDG_CONFIG_HOME:-${HOME}/.config/}/aqua/aqua-policy.yaml` and you allow this policy by `aqua policy allow` command
- AQUA_POLICY_CONFIG isn't set
- you expect the policy file should be applied against `${HOME}/.local/share/chezmoi/private_dot_config/exact_aqua/aqua.yaml`

```
${HOME}/.local/share/chezmoi/private_dot_config/exact_aqua/
  aqua.yaml
${XDG_CONFIG_HOME:-${HOME}/.config/}/aqua/aqua-policy.yaml
```

Is my understanding correct?
If so, you are misunderstanding the specification of the policy.
This is expected behaviour.
Indeed, the specification of Policy is a little complicated and confusing.

https://aquaproj.github.io/docs/reference/security/policy-as-code/#policy-types

aqua looks for Policy files from `the Git repository root directory` and the environment variable `AQUA_POLICY_CONFIG`.
If you want to apply the global config `AQUA_GLOBAL_CONFIG`, there are two options.

## 1. Manage global config and policy file with Git (Recommended)

```
dotfiles/ # Git repository
  aqua.yaml
  aqua-policy.yaml
```

## 2. Specify the policy file with `AQUA_POLICY_CONFIG`

```sh
export AQUA_POLICY_CONFIG="$ABSOLUTE_PATH_TO_AQUA_POLICY_YAML:$AQUA_POLICY_CONFIG"
```

**Reply by suzuki-shunsuke** [reply]
> "AQUA_POLICY_CONFIG": "/Users/(USER)/.config/aqua/aqua-policy.yaml",

Oh, sorry. You set `AQUA_POLICY_CONFIG`.

**Reply by suzuki-shunsuke** [reply]
Oh, I see. I think the path of `registry.yaml` is wrong.

```
${HOME}/
  .local/share/chezmoi/private_dot_config/exact_aqua/
    aqua.yaml
    registry.yaml
  .config/aqua/aqua-policy.yaml
```

The policy file allowed `$HOME/.config/aqua/registry.yaml`, not `.local/share/chezmoi/private_dot_config/exact_aqua/registry.yaml`.


```yaml
# aqua-policy.yaml
registries:
  - name: local
    type: local
    path: registry.yaml # Relative path from aqua-policy.yaml
```

```yaml
# aqua.yaml
registries:
  - name: local
    type: local
    path: registry.yaml # Relative path from aqua.yaml
```
