### DISCUSSION TITLE
AQUA_DISABLE_POLICY doesn't work

### DISCUSSION THREAD

**Discussion by scai-splunk** [aquaproj/aqua#2414] [Deprecated (Bug Report)] [answered]
### aqua info

```console
$ aqua info
{
  "version": "2.16.2",
  "commit_hash": "8cf52f4af1fa61e71c61849bc18f956a1bd815e4",
  "os": "darwin",
  "arch": "arm64",
  "pwd": "/Users/(USER)",
  "root_dir": "/Users/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "AQUA_DISABLE_POLICY": "true",
    "AQUA_GLOBAL_CONFIG": "/Users/(USER)/.config/aquaproj-aqua/aqua.yaml"
  },
  "config_files": []
}
```

#### aqua < v2.10.0

```console
$ aqua -v

```

OS (Windows, Linux, macOS, etc): macOS
CPU Architecture (amd64, arm64, etc): arm64

### Overview

AQUA_DISABLE_POLICY does not work

I've set AQUA_DISABLE_POLICY to true, but when i run `aqua i -a`

I still get
```console
ERRO[0000] install the package                           aqua_version=2.16.2 doc="https://aquaproj.github.io/docs/reference/codes/002" env=darwin/arm64 error="this package isn't allowed" package_name=some/package package_version=v0.15.2 program=aqua registry=local
```

### How to reproduce

aqua.yaml

```yaml
registries:
- name: local
  type: local
  path: registry.yaml
- type: standard
  ref: v4.76.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: junegunn/fzf@0.43.0
- name: kubernetes/kubectl@v1.25.15
- name: kubernetes-sigs/kind@v0.20.0
......
- name: some/package@0.2.2
  registry: local
```

Other related code such as local Registry

```

```

Executed command and output

```console
$ 
```

### Debug output

```console
$ 
```

### Expected behaviour

install of local package successful

### Actual behaviour

error="this package isn't allowed" 

### Reference

*
