### DISCUSSION TITLE
Any suggestions on properly handling `toolchain go1.xx.xx` with aqua based project?

### DISCUSSION THREAD

**Discussion by sheldonhull** [aquaproj/aqua#2609] [Deprecated (Question and Answer)] [answered]
### Question

I've been using aqua based go in my pipelines, via a pipeline style script. 

Now, when doing this we run into a problem. 
I have aqua managing go, but now Go has a declaration that explicitly controls the toolchain version. This is excellent but means I now have double places to maintain.

However, it will mean that Go not kept in sync with aqua + go.mod toolchain version will result in downloading an aqua managed go then again having to redownload another Go based on the toolchain. This can double the step time.

### Example Code

Useful code perhaps for azure pipeline example, though this needs toolchain support to better handle this situation.

```yaml
---
parameters:
  # - name: GO_VERSION # set dynamically in the task
  #   type: string
  #   default: 1.x
  - name: GOPATH
    type: string
    default: $(Agent.HomeDirectory)/go
  - name: workingDirectory
    type: string
    default: $(Build.SourcesDirectory)
steps:
  - bash: |
      # Search for the aqua.yaml file
      if [[ -f "aqua.yaml" ]]; then
          file="aqua.yaml"
      elif [[ -f "aqua/aqua.yaml" ]]; then
          file="aqua/aqua.yaml"
      elif [[ -f ".aqua/aqua.yaml" ]]; then
          file=".aqua/aqua.yaml"
      else
          echo "Error: aqua.yaml file not found."
          echo "##vso[task.logissue type=warning]unable to find aqua config, behavior with tools might unpredictable"
      fi
      echo "found aqua.yaml at: $file"
      GO_VERSION=$(grep -oP 'golang/go@go\K[\d\.]+' "${file}")
      echo "##vso[task.setvariable variable=GO_VERSION;isreadonly=true;isoutput=true;]${GO_VERSION}"
      echo "##vso[task.setvariable variable=GO_VERSION;isreadonly=true;]${GO_VERSION}"
      echo "👉 use go version: ${GO_VERSION}"
    displayName: set-go-version
    name: getgoversion
    workingDirectory: ${{ parameters.workingDirectory }}
  - task: GoTool@0
    displayName: install-go
    inputs:
      version: $(getgoversion.GO_VERSION)
      goPath: $(GOPATH)
```

You could use this in the docs if you like, perhaps it would be useful.
The reason this is needed is because you can get tool mismatch if you use any tools with a different system level Go (like Mage). 

### Note

Any ideas on how you'd handle? 

Aqua running `aqua update --ignore-gomod` or equivalent that would allow updating toolchain version to be kept in sync with `go.mod`, but allowing override to ignore it otherwise?

Maybe a grouped go.mod + aqua renovate dependency so they both get updated in sync together with renovate? 

Just looking for a fresh perspective so I don't have more confusing steps in the future for contributors.

**Comment by suzuki-shunsuke** [comment]
Thank you for your question.
I'm not familiar with Go toolchain, so now I'm looking into it.

https://go.dev/doc/toolchain

I found that if the go version in aqua.yaml is older than the go version of go directive in go.mod, go is installed twice.

> When the go or toolchain line is newer than the bundled toolchain, the go command runs the newer toolchain instead.
> For example, when using the go command bundled with Go 1.21.3 in a main module that says go 1.21.9, the go command finds and runs Go 1.21.9 instead.

## How to reproduce

1. Set up

Install aqua on a container.

https://aquaproj.github.io/docs/tutorial/#docker

```sh
docker run --rm -ti debian:bookworm-20231009 bash
```

```sh
apt update
apt install -y curl vim

mkdir ~/workspace
cd ~/workspace
export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
curl -sSfL -O https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.2.0/aqua-installer
echo "d13118c3172d90ffa6be205344b93e8621de9bf47c852d80da188ffa6985c276  aqua-installer" | sha256sum -c
chmod +x aqua-installer
./aqua-installer
```

```console
$ aqua version
aqua version 2.21.3 (8ddf104abfab2feb15018280c53ec9936aeff31e)
```

2. Install Go 1.21.0 by aqua.

```sh
aqua init
aqua g -i golang/go@go1.21.0
aqua i
```

aqua.yaml

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.114.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.21.0
```

3. Check Go version

```console
$ go version
go version go1.21.0 linux/arm64
```

4. Create go.mod and change go directive to 1.21.5, which is newer than go version in aqua.yaml

```console
go mod init foo
sed -i s/1.21.0/1.21.5/ go.mod
```

go.mod

```
module foo

go 1.21.5
```

5. Check go version

```console
$ go version
go: downloading go1.21.5 (linux/arm64)
go version go1.21.5 linux/arm64
```

We can confirm when go version is run

1. go 1.21.5 is installed
2. `go version` is different from the version in aqua.yaml

**Reply by suzuki-shunsuke** [reply]
This issue occurs if go in aqua.yaml is newer or equal than 1.21.0 and is older than toolchain.

**Reply by suzuki-shunsuke** [reply]
We can solve the issue if we can make go version in aqua.yaml same with version of toolchain.

**Reply by suzuki-shunsuke** [reply]
actions/setup-go supports getting go version from go.mod.

https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file

If aqua can do the same thing, we can solve the issue.

This is just one idea.

e.g.

```yaml
packages:
  - name: golang/go
    go-version-file: go.mod
```
