### DISCUSSION TITLE
Github Enterprise Private Registry

### DISCUSSION THREAD

**Discussion by bhundven** [aquaproj/aqua#2726] [Deprecated (Question and Answer)] [answered]
### Question

At my work we use GitHub Enterprise Server (GHES). We have projects that create release, and I'd like to use aqua for those release and have a private registry for those projects.
I'm trying to follow the documentation, but I'm wondering if anyone else has experience with this scenario?

**Comment by suzuki-shunsuke** [comment, marked as answer]
Thank you for your feedback.
Unfortunately, aqua doesn't support GitHub Enterprise at the moment.

**Reply by suzuki-shunsuke** [reply]
Let's consider the specification of GitHub Enterprise Support.

## Idea 1

https://pkg.go.dev/github.com/google/go-github/v60/github#Client.WithEnterpriseURLs

> WithEnterpriseURLs returns a copy of the client configured to use the provided base and upload URLs. If the base URL does not have the suffix "/api/v3/", it will be added automatically. If the upload URL does not have the suffix "/api/uploads", it will be added automatically.
> 
> Note that WithEnterpriseURLs is a convenience helper only; its behavior is equivalent to setting the BaseURL and UploadURL fields.
> 
> Another important thing is that by default, the GitHub Enterprise URL format should be http(s)://[hostname]/api/v3/ or you will always receive the 406 status code. The upload URL format should be http(s)://[hostname]/api/uploads/.

A field `github_enterprise` is added.

### GitHub Access Token

The environment variable `GITHUB_TOKEN` and `AQUA_GITHUB_TOKEN` are used for GitHub Cloud rather than GitHub Enterprise Server.

So aqua should support other environment variables like `GITHUB_ENTERPRIZE_TOKEN` and `AQUA_GITHUB_ENTERPRIZE_TOKEN`.

In case of GitHub CLI, `GH_ENTERPRISE_TOKEN` is used.

https://cli.github.com/manual/#github-enterprise

The prefix `GITHUB_` is unavailable in GitHub Actions, so `GH_ENTERPRISE_TOKEN` and `AQUA_GH_ENTERPRISE_TOKEN` are better.

https://docs.github.com/en/actions/learn-github-actions/variables#naming-conventions-for-configuration-variables

> Names must not start with the GITHUB_ prefix.

### github_content registry

https://aquaproj.github.io/docs/reference/config/#github_content-registry

```yaml
registries:
  - name: foo
    type: github_content
    github_enterprise:
      base_url: htttps://example.com
      upload_url: htttps://example.com
    repo_owner: aquaproj
    repo_name: aqua-registry
    ref: v3.90.0 # renovate: depName=aquaproj/aqua-registry
    path: registry.yaml
```

### packages

https://aquaproj.github.io/docs/reference/registry-config/#package-types

```yaml
packages:
- type: github_release
  github_enterprise:
    base_url: htttps://example.com
    upload_url: htttps://example.com
  repo_owner: aquaproj
  repo_name: example
```

## Idea 2

This specification supports multiple GitHub Enterprise Servers and prevents conflicts of environment variables.

### registry.yaml

Add `.hosts` and `.packages[].host`.

```yaml
hosts:
- name: example
  github_enterprise:
    base_url: htttps://example.com
    upload_url: htttps://example.com
packages:
- type: github_release
  host: example
  repo_owner: aquaproj
  repo_name: example
```

### aqua.yaml

Add `.hosts` and `.registries[].host`.

```yaml
hosts:
  - name: example
    github_enterprise:
      base_url: htttps://example.com
      upload_url: htttps://example.com
      token_env: GH_ENTERPRISE_TOKEN
    hosts:
      - name: example
        token_env: GH_ENTERPRISE_TOKEN
registries:
  - name: foo
    type: github_content
    host: example
    repo_owner: aquaproj
    repo_name: aqua-registry
    ref: v3.90.0
    path: registry.yaml
```
