### DISCUSSION TITLE
Pinning to major and/or minor versions along with renovate

### DISCUSSION THREAD

**Discussion by bhundven** [aquaproj/aqua#2749] [Deprecated (Question and Answer)] [answered]
### Question

This is related to #2747 and #2354, where the "latest release" is not the same as the "latest version", but it got me curious in a repository where I am also using renovate to keep versions up to date with the latest release of a specific version.

Say I have `kubectl` requirement of staying at `v1.29.x`, and `v1.30.0` is released, but I don't want to go to `v1.30.0`, I'd like to stay at `v1.29.x`.

The latest version of `kubectl` is at `v1.29.3`. Say `v1.30.0` releases, but I'd like to stick to `v1.29.3` until `v1.29.4` is released.

Without using renovate, `aqua up` will automatically update to the "latest version". I'm looking for a way to pin to the major or minor version of a release.

With using renovate, I'm not aware of a way to pin packages like this with `aqua-renovate-config`.

### Background of the question

I use the example of `kubectl` from #2747, but say I were to use `packer` or `terraform` as the package, because when you upgrade to a newer minor version, you may have to refactor code(hcl2) to fix any breaking changes the new minor or even major version might introduce. But new releases (`maj`.`min`.`release`) may have non-breaking bug fixes or CVE fixes.

**Comment by suzuki-shunsuke** [comment, marked as answer]
Thank you for your feedback.
Regarding Renovate, I think you can disable major and minor updates like this.

```json
   "packageRules": [
      {
        "packageNames": ["kubernetes/kubectl"],
        "matchupdatetypes" ["major", "minor"],
        "enabled": false
      }
   ]
```

Regarding `aqua up` command, aqua doesn't support this yet.
I think it would be great if aqua supports this feature.

**Reply by suzuki-shunsuke** [reply]
This is just one idea.

```yaml
  - name: golang/vuln/govulncheck@v1.0.3
    update:
      # If enabled is false, aqua up command ignores the package.
      # If the package name is passed to aqua up command explicitly, enabled is ignored.
      # By default, enabled is true.
      enabled: false
      # The condition of allowed version.
      # expr https://github.com/expr-lang/expr is used.
      # By default, all versions are allowed.
      # The version must meet both allowed_version and types.
      allowed_version: semver("<= 1.5.0")
      # The list of allowed update types
      # By default, all types are allowed.
      # major, minor, patch, other
      types:
        - minor
```
