### DISCUSSION TITLE
[Q & A] How can I install different versions for a specific tool in the same project?

### DISCUSSION THREAD

**Discussion by yanolab** [aquaproj/aqua#3159] [Deprecated (Question and Answer)] [answered]
### Question

How can I install and use different versions for a specific tool version in the same project?

For example, workflow-a requires node@20 but other workflow can use node@22.

### Background of the question

Sometimes CI workflow requires different tool versions such as node.
In this case, I want to use a command alias for a specific command.
For example, 

```yaml
  - name: nodejs/node@v20.9.0 # for specific ci
  	command: node20
  - name: nodejs/node@v22.9.0 # default
```

There is a feature for aliasing for package name but it seems not a command.
https://aquaproj.github.io/docs/reference/registry-config/aliases/#use-aliases-only-for-keeping-the-compatibility
