### DISCUSSION TITLE
Will there be support for PHP (and its tools)?

### DISCUSSION THREAD

**Discussion by assyrus-favolo** [aquaproj/aqua#3204] [Deprecated (Question and Answer)] [answered]
### Question

I'd love to use this tool to keep my team's PHP and Composer versions in line with each other, do you think it would be possible to add them in the future?

### Background of the question

I want to leverage all great aspects of this system like easier onboarding, reproducibility, etc.

### Example Code

How the configuration could look

```yaml
packages:
- name: php/php@vA.B.C
- name: composer/composer@vD.E.F
```
