### DISCUSSION TITLE
v0.9.0

### DISCUSSION THREAD

**Discussion by suzuki-shunsuke** [aquaproj/aqua#528] [Announcements]
[Pull Requests](https://github.com/aquaproj/aqua/pulls?q=is%3Apr+is%3Aclosed+milestone%3Av0.9.0) | [Issues](https://github.com/aquaproj/aqua/issues?q=is%3Aissue+milestone%3Av0.9.0+is%3Aclosed) | https://github.com/aquaproj/aqua/compare/v0.8.13...v0.9.0-0

## ⚠️ Breaking Changes

#520 #521 Remove `inline_registry`

### How to migrate

Use `local` Registry instead of `inline` Registry.

https://aquaproj.github.io/docs/reference/config

AS IS

aqua.yaml

```yaml
inline_registry:
  packages:
  - type: github_release
    repo_owner: suzuki-shunsuke
    repo_name: cmdx
    asset: 'cmdx_{{trimV .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
```

TO BE

aqua.yaml

```yaml
registries:
- name: inline
  type: local
  path: registry.yaml
```

registry.yaml

```yaml
packages:
- type: github_release
  repo_owner: suzuki-shunsuke
  repo_name: cmdx
  asset: 'cmdx_{{trimV .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
```

## Feature

#511 #512 Retry installing a package when it failed to install the package due to `file already exists` error
#513 #518 Add `registry_ref` in the error log

## Bug Fixes

#519 Fix the file permission of `aqua.yaml` which is generated by `aqua init` command

Change the file permission from `0755` to `0644`.
Executable permission isn't needed.

## Others

#515 #516 #517 Refactoring

<hr /><em>This discussion was created from the release <a href='https://github.com/aquaproj/aqua/releases/tag/v0.9.0'>v0.9.0</a>.</em>
