### ISSUE TITLE
Support importing external aqua.yaml

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1032]
## Feature Overview

Support importing external aqua.yaml.

## Why is the feature needed?

> Please explain the problem you want to solve.

This is useful to manage multiple repositories tools in one place.

## Does the feature include Breaking Changes?

Probably No.

## Example Code

> command and configuration

aqua.yaml

```yaml
registries:
  - type: standard
    ref: v3.16.0

packages:
  - import_external:
      # https://github.com/suzuki-shunsuke/tfcmt/blob/v3.2.5/aqua.yaml
      type: github_content # url, github_archive
      repo_owner: suzuki-shunsuke
      repo_owner: tfcmt
      ref: v3.2.5 # renovate: depName=suzuki-shunsuke/tfcmt
      path: aqua.yaml
```
