### ISSUE TITLE
Support template in `go_install` package's `path` attribute

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1084]
## Feature Overview

Support template in `go_install` package's `path` attribute.

## Why is the feature needed?

> Please explain the problem you want to solve.

Go Module package includes the major version.
Without template, we have to define version_constraint per major version.
It isn't desirable.

sprig supports functions about semantic versioning.

http://masterminds.github.io/sprig/semver.html

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

registry.yaml

https://github.com/volatiletech/sqlboiler

```yaml
packages:
  - type: go_install
    repo_owner: volatiletech
    repo_name: sqlboiler
    description: Generate a Go ORM tailored to your database schema
    path: github.com/volatiletech/sqlboiler/v{{(semver .Version).Major}}
```
