### ISSUE TITLE
`files` doesn't work in `go_install` package

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1085]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 1.18.0 (4c4a265975fdbbd0e85f4f75d5533478e7ed367c)
```

## Environment

* OS (Windows, Linux, macOS, etc): darwin
* CPU Architecture (amd64, arm64, etc): arm64

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

aqua.yaml

```yaml
---
registries:
  - name: standard
    type: local
    path: registry.yaml
packages:
  - name: volatiletech/sqlboiler@v4.12.0
```

registry.yaml

```yaml
packages:
  - type: go_install
    repo_owner: volatiletech
    repo_name: sqlboiler
    path: github.com/volatiletech/sqlboiler/v4
    files:
      - name: sqlboiler
```

```console
$ aqua which sqlboiler
/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/go_install/github.com/volatiletech/sqlboiler/v4/v4.12.0/bin/v4
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ 
```

## Expected Behaviour

```console
$ aqua which sqlboiler
/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/go_install/github.com/volatiletech/sqlboiler/v4/v4.12.0/bin/sqlboiler
```

## Actual Behaviour

```console
$ aqua which sqlboiler
/Users/shunsukesuzuki/.local/share/aquaproj-aqua/pkgs/go_install/github.com/volatiletech/sqlboiler/v4/v4.12.0/bin/v4
```

## References

*
