### ISSUE TITLE
`aqua g -i`: Support inserting to imported file

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1086]
## Feature Overview

aqua supports importing files.

```yaml
registries:
- type: standard
  ref: v3.22.0
packages:
- import: aqua/*.yaml
```

I'd like to add an option to insert packages to an imported file.

## Why is the feature needed?

> Please explain the problem you want to solve.

## Example Code

> command and configuration

Create or update a file.

```console
$ aqua g -o aqua/tfcmt.yaml suzuki-shunsuke/tfcmt
```

`-o` options implies `-i`.
