### ISSUE TITLE
`aqua g -i`: Support setting a default inserted file in `aqua.yaml`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1091]
## Feature Overview

Support setting a default inserted file by `aqua g -i` in `aqua.yaml`.

## Why is the feature needed?

> Please explain the problem you want to solve.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ aqua g -i suzuki-shunsuke/tfcmt
```

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v3.23.0 # renovate: depName=aquaproj/aqua-registry
generate:
  out: aqua/default.yaml
packages:
  - import: aqua/*.yaml
```
