### ISSUE TITLE
Add option to execute command after downloading assets

### ISSUE THREAD

**Issue by katainaka0503** [aquaproj/aqua#1111]
## Feature Overview
It is useful if aqua can execute some commands after downloading assets.

## Why is the feature needed?

> Please explain the problem you want to solve.

To install AWS CLI on mac or windows, we have to execute some commands to execute installer.

https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

## Does the feature include Breaking Changes?
I think no.

## Example Code

> command and configuration

```console
$ aqua install 
```

```yaml
packages:
  - type: http
    repo_owner: aws
    repo_name: aws-cli
    description: The AWS Command Line Interface (AWS CLI) is a unified tool that provides a consistent interface for interacting with all parts of Amazon Web Services
    search_words:
      - Linux Only
    version_source: github_tag
    url: https://awscli.amazonaws.com/AWSCLIV2-{{.Version}}.pkg
    format: raw
    execute: "installer -pkg AWSCLIV2-{{.Version}}.pkg -target someDirectory -applyChoiceChangesXML choices.xml"
    supported_envs:
      - darwin
```
