### ISSUE TITLE
Support changing template engine for performance

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1161]
## Feature Overview

aqua uses [text/template](https://pkg.go.dev/text/template) at the moment.
I propose to support changing template engine for performance.

## Why is the feature needed?

> Please explain the problem you want to solve.

To improve the performance.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

registry.yaml

```yaml
template_engine:
  type: pongo2 # By default, text/template
packages:
  - type: github_release
    # ...
    asset: genact-{{Version}}-{{OS}}-{{Arch}}
```

## Note

It makes the merge of registry files difficult.
I don't have a strong motivation to support this feature at the moment.
But I'm interested in how this feature improves the performance.

## Reference

- https://blog.logrocket.com/golang-template-libraries-performance-comparison/
