### ISSUE TITLE
Support a template variable `URL`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1231]
## Feature Overview

Support a template variable `URL`.

## Why is the feature needed?

> Please explain the problem you want to solve.

To make checksum configuration simple.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ 
```

```yaml
packages:
  - type: http
    repo_owner: helm
    repo_name: helm
    url: https://get.helm.sh/helm-{{.Version}}-{{.OS}}-{{.Arch}}.tar.gz
    checksum:
      type: http
      url: "{{.URL}}.sha256sum"
```
