### ISSUE TITLE
Prevent registries from being tampered

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1379]
## Feature Overview

Prevent registries from being tampered.

## Why is the feature needed?

> Please explain the problem you want to solve.

To prevent malicious tools from being installed and executed.

## How

TBD.

* checksum
* signing

## Does the feature include Breaking Changes?

Probably no.

## Example Code

> command and configuration

```console
$ 
```

```yaml

```

**Comment by suzuki-shunsuke** [comment]
```yaml
registries:
- name: foo
  type: github_content
  repo_owner: aquaproj
  repo_name: aqua-registry
  ref: v3.90.0 # renovate: depName=aquaproj/aqua-registry
  path: registry.yaml
  cosign:
    cosign_experimental: true
    opts:
      - --signature
      - https://github.com/aquaproj/aqua-registry/releases/download/{{.Version}}/registry.yaml.sig
      - --certificate
      - https://github.com/aquaproj/aqua-registry/releases/download/{{.Version}}/registry.yaml.pem
```

**Comment by suzuki-shunsuke** [comment]
- key
- certificate
- signature

```yaml
cosign:
  signature:
    type: github_release
    asset: registry.yaml.sig
  certificate:
    type: github_release
    asset: registry.yaml.pem
  key:
    type: github_release
    asset: registry.yaml.key
```
