### ISSUE TITLE
Prevent too huge files from being downloaded

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1422]
## Feature Overview

Prevent too huge files from being downloaded.
If a downloaded file is too huge, the download is canceled and the installation fails.

## Why is the feature needed?

> Please explain the problem you want to solve.

It is required to prevent the attack that let too huge files being downloaded.

## Does the feature include Breaking Changes?

Basically No.

## Example Code

registry.yaml

`max_asset_size` is added.

```yaml
packages:
  - type: github_release
    repo_owner: suzuki-shunsuke
    repo_name: tfcmt
    asset: tfcmt_{{.OS}}_{{.Arch}}.tar.gz
    max_asset_size: 10 # 10MB. By default, 1GB 
    checksum:
      type: github_release
      max_asset_size: 1 # 1MB. By default, 1MB
      asset: tfcmt_{{trimV .Version}}_checksums.txt
      file_format: regexp
      algorithm: sha256
      pattern:
        checksum: "^(\\b[A-Fa-f0-9]{64}\\b)"
        file: "^\\b[A-Fa-f0-9]{64}\\b\\s+(\\S+)$"
```
