### ISSUE TITLE
`aqua g --pin` generates broken configuration

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1462]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 1.25.0 (9a544d686c6b7898596dd4a44cd04bd3a2782473)
```

## Environment

* OS (Windows, Linux, macOS, etc): darwin
* CPU Architecture (amd64, arm64, etc): arm64

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

```yaml
registries:
- type: standard
  ref: f83e6465256285517e393b149e0458b3cbee7928 # renovate: tag=v3.106.0 depName=aquaproj/aqua-registry
packages:
```

```console
$ aqua g --pin 
WARN[0001] same package already exists                   aqua_version= env=darwin/arm64 package_name=1xyz/pryrite package_registry=standard program=aqua
- name: 1xyz/pryrite
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ 
```

## Important Factoids

The warning `same package already exists` occurs wrongly.

## References

*
