### ISSUE TITLE
aqua.yaml's registries: support `private` field for private registries

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1468]
## Feature Overview

Similar to https://github.com/aquaproj/aqua/issues/1466 , but for not private packages but private registries.

## Why is the feature needed?

> Please explain the problem you want to solve.

Same as https://github.com/aquaproj/aqua/issues/1466

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ 
```

https://aquaproj.github.io/docs/reference/config#github_content-registry

```yaml
registries:
- name: foo
  type: github_content
  repo_owner: aquaproj
  repo_name: aqua-registry
  ref: v3.90.0 # renovate: depName=aquaproj/aqua-registry
  private: true
  path: registry.yaml
```
