### ISSUE TITLE
Add the attribute `version_prefix` to Registry Configuration

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1545]
## Feature Overview

- Add the attribute `version_prefix` to Registry Configuration
- Add the parameter `SemVer` to [expr expressions](https://aquaproj.github.io/docs/reference/registry-config/version-overrides/) and [template variables](https://aquaproj.github.io/docs/reference/registry-config/template/#template-variables)
- versions are filtered by this attribute same as [version_filter](https://aquaproj.github.io/docs/reference/registry-config/version-filter)
  - We would be able to replace `version_filter` to `version_prefix` in almost cases
- Instead of `Version`, the parameter `Semver` is used in the function `semver`

## Why is the feature needed?

> Please explain the problem you want to solve.

Make Registry Configuration simple.

## Does the feature include Breaking Changes?

No. But maybe we would create an issue to deprecate and remove `version_filter`.

## Example Code

> command and configuration

```console
$ 
```

[kubernetes-sigs/kustomize](https://github.com/aquaproj/aqua-registry/blob/edadc10a236d119af5702406d238fea8858265dd/pkgs/kubernetes-sigs/kustomize/registry.yaml)

AS IS

```yaml
  - type: github_release
    repo_owner: kubernetes-sigs
    repo_name: kustomize
    asset: kustomize_{{trimPrefix "kustomize/" .Version}}_{{.OS}}_{{.Arch}}.tar.gz
    version_filter: Version startsWith "kustomize/"
    version_constraint: semverWithVersion(">= 4.5.4", trimPrefix(Version, "kustomize/"))
    version_overrides:
      - version_constraint: semverWithVersion(">= 4.4.1", trimPrefix(Version, "kustomize/"))
        supported_envs:
          - linux
          - darwin
          - amd64
      - version_constraint: semverWithVersion(">= 4.2.0", trimPrefix(Version, "kustomize/"))
        supported_envs:
          - linux
          - darwin
      - version_constraint: semverWithVersion("< 4.2.0", trimPrefix(Version, "kustomize/"))
        rosetta2: true
        supported_envs:
          - linux
          - darwin
          - amd64
```

TO BE

```yaml
  - type: github_release
    repo_owner: kubernetes-sigs
    repo_name: kustomize
    version_prefix: kustomize/
    asset: kustomize_{{.SemVer}}_{{.OS}}_{{.Arch}}.tar.gz
    version_constraint: semver(">= 4.5.4")
    version_overrides:
      - version_constraint: semver(">= 4.4.1")
        supported_envs:
          - linux
          - darwin
          - amd64
      - version_constraint: semver(">= 4.2.0")
        supported_envs:
          - linux
          - darwin
      - version_constraint: semver("< 4.2.0")
        rosetta2: true
        supported_envs:
          - linux
          - darwin
          - amd64
```

**Comment by suzuki-shunsuke** [comment]
AS IS

```yaml
  - type: github_release
    repo_owner: tamasfe
    repo_name: taplo
    version_constraint: semver(">= 0.8.0")
    asset: taplo-{{.OS}}-{{.Arch}}.{{.Format}}
    replacements:
      amd64: x86_64
      arm64: aarch64
    supported_envs:
      - darwin
      - linux
      - windows/amd64
    format: gz
    files:
      - name: taplo
        src: taplo-{{.OS}}-{{.Arch}}
    overrides:
      - goos: windows
        format: zip
        files:
          - name: taplo
            src: taplo.exe
    version_overrides:
      - version_constraint: Version startsWith "release-taplo-cli-"
        asset: taplo-{{.Arch}}-{{.OS}}-gnu.{{.Format}}
        rosetta2: true
        format: tar.gz
        supported_envs:
          - darwin
          - linux/amd64
        replacements:
          amd64: x86_64
          darwin: apple-darwin
          linux: unknown-linux
        overrides: []
        files:
          - name: taplo
      - version_constraint: Version startsWith "release-cli-" and semverWithVersion(">= 0.6.0", trimPrefix(Version, "release-cli-"))
        asset: taplo-{{trimPrefix "release-cli-" .Version}}-{{.Arch}}-{{.OS}}-gnu.{{.Format}}
        rosetta2: true
        format: tar.gz
        supported_envs:
          - darwin
          - linux/amd64
        replacements:
          amd64: x86_64
          darwin: apple-darwin
          linux: unknown-linux
        overrides: []
        files:
          - name: taplo
      - version_constraint: Version startsWith "release-cli-" and semverWithVersion("<= 0.5.0", trimPrefix(Version, "release-cli-"))
        asset: taplo-{{.Arch}}-{{.OS}}-gnu.{{.Format}}
        format: tar.gz
        rosetta2: true
        replacements:
          amd64: x86_64
          darwin: apple-darwin
          linux: unknown-linux
          windows: pc-windows
        files:
          - name: taplo
        overrides:
          - goos: windows
            format: zip
        supported_envs:
          - darwin
          - amd64
```

TO BE

```yaml
  - type: github_release
    repo_owner: tamasfe
    repo_name: taplo
    version_constraint: semver(">= 0.8.0")
    asset: taplo-{{.OS}}-{{.Arch}}.{{.Format}}
    replacements:
      amd64: x86_64
      arm64: aarch64
    supported_envs:
      - darwin
      - linux
      - windows/amd64
    format: gz
    files:
      - name: taplo
        src: taplo-{{.OS}}-{{.Arch}}
    overrides:
      - goos: windows
        format: zip
        files:
          - name: taplo
            src: taplo.exe
    version_overrides:
      - version_constraint: "true"
        version_prefix: release-taplo-cli-
        asset: taplo-{{.Arch}}-{{.OS}}-gnu.{{.Format}}
        rosetta2: true
        format: tar.gz
        supported_envs:
          - darwin
          - linux/amd64
        replacements:
          amd64: x86_64
          darwin: apple-darwin
          linux: unknown-linux
        overrides: []
        files:
          - name: taplo
      - version_constraint: semver(">= 0.6.0")
        version_prefix: release-cli-
        asset: taplo-{{.SemVer}}-{{.Arch}}-{{.OS}}-gnu.{{.Format}}
        rosetta2: true
        format: tar.gz
        supported_envs:
          - darwin
          - linux/amd64
        replacements:
          amd64: x86_64
          darwin: apple-darwin
          linux: unknown-linux
        overrides: []
        files:
          - name: taplo
      - version_constraint: "true"
        version_prefix: release-cli-
        asset: taplo-{{.Arch}}-{{.OS}}-gnu.{{.Format}}
        format: tar.gz
        rosetta2: true
        replacements:
          amd64: x86_64
          darwin: apple-darwin
          linux: unknown-linux
          windows: pc-windows
        files:
          - name: taplo
        overrides:
          - goos: windows
            format: zip
        supported_envs:
          - darwin
          - amd64
```
