### ISSUE TITLE
Support `aqua update` command updating packages and registries

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1657]
## Feature Overview

Add a command to update packages and registries.

## Why is the feature needed?

> Please explain the problem you want to solve.

Feedback from @sheldonhull

> Upgrade an aqua config without renovate. I'm a huge fan of renovate but it's a huge ask for folks to all use it especially if they are just setting up a global tools config.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

Prepare aqua.yaml which contains old registries and packages

```yaml
registries:
- type: standard
  ref: v3.90.0 # Old
packages:
- name: cli/cli@v2.0.0 # Old
- name: junegunn/fzf@0.28.0 # Old
```

Run `aqua update`.

```console
$ aqua update
```

Then all registries and packages are updated.

```yaml
registries:
- type: standard
  ref: v3.166.1 # Updated
packages:
- name: cli/cli@v2.23.0 # Updated
- name: junegunn/fzf@0.38.0 # Updated
```

Support `-tag`. https://aquaproj.github.io/docs/tutorial-extras/package-tag/

```console
aqua update -t dev
```

## Ideas

1. Support version constraint like `^1.0.0`
2. Add a field to exclude update

```yaml
packages:
- name: cli/cli@v2.0.0
  exclude_update: true
```

I prefer `3` than `2`.

3. Exclude packages using long syntax

```yaml
packages:
- name: cli/cli@v2.0.0 # Update
- name: cli/cli
  version: v2.0.0 # Don't update
```

4. Conform to [policy](https://aquaproj.github.io/docs/tutorial-extras/policy-as-code/)

This is nice to have but isn't mandatory.
I guess it is a bit difficult to implement this feature.

## Reference

- https://github.com/aquaproj/aqua/discussions/1651
- https://github.com/aquaproj/aqua/pull/577

**Comment by CrystalMethod** [comment]
This exact question came up today in my project team. A must have is that `update` respects pinned versions and leaves them unchanged.

**Comment by suzuki-shunsuke** [comment]
> A must have is that update respects pinned versions and leaves them unchanged.

What do you mean?
aqua forces to pin all registries and packages versions, so I can't understand what you want.
Do you expect version constraint like `^1.0.0`?

**Comment by suzuki-shunsuke** [comment]
I like and strongly recommend Renovate, so I'd like to know why users who want this feature don't use Renovate.

**Comment by CrystalMethod** [comment]
> I like and strongly recommend Renovate, so I'd like to know why users who want this feature don't use Renovate.

In my case: because the company policies do not allow it. It is not allowed - or requires a separate and lengthy review/audit - to use such managed services. We are experimenting with running Renovate selfhosted, but it is not the same.

**Comment by suzuki-shunsuke** [comment]
Thank you for your explanation.

**Comment by CrystalMethod** [comment]
Currently I try to use `updatecli` for this - maybe this is a good companion, because it supports other systems as well. This could be a suitable replacement for Renovate; at least in my case.

**Comment by suzuki-shunsuke** [comment]
I don't know [updatecli](https://www.updatecli.io/) well, but I wonder you can update `aqua.yaml` by updatecli.
If so, it can be used instead of `aqua update` command.

And I think [Self hosted Renovate by GitHub Actions](https://github.com/renovatebot/github-action) is also useful if it is allowed in your company.
This is just a GitHub Actions, so the hosting isn't difficult.

**Comment by CrystalMethod** [comment]
> I don't know [updatecli](https://www.updatecli.io/) well, but I wonder you can update `aqua.yaml` by updatecli. If so, it can be used instead of `aqua update` command.

I am working on a PoC for this and will share my findings.

> And I think [Self hosted Renovate by GitHub Actions](https://github.com/renovatebot/github-action) is also useful if it is allowed in your company. This is just a GitHub Actions, so the hosting isn't difficult.

This is a completely different story: we are using the self-hosted Bitbucket (formerly known as Stash) and finishing the migration to GitHub Enterpise will take several more months.

**Comment by suzuki-shunsuke** [comment]
> I am working on a PoC for this and will share my findings.

Thanks. I'm looking forward to it. I'll also take a look updatecli when I have a time.

> This is a completely different story: we are using the self-hosted Bitbucket (formerly known as Stash) and finishing the migration to GitHub Enterpise will take several more months.

Oh, I see.

**Comment by CrystalMethod** [comment]
##### aqua.yaml
```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v3.138.0
packages:
- name: argoproj/argo-cd@v2.6.3
- name: dagger/dagger@v0.3.12 # latest is v0.3.13
- name: kubernetes/kubectl
  version: v1.24.10
```

##### updatecli.dagger.yaml
```yaml
name: Update Dagger GitHub Release

sources:
  dagger:
    name: Get latest Dagger version from GitHub releases
    kind: githubrelease
    spec:
      owner: dagger
      repository: dagger
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      versionfilter:
        kind: regex
        pattern: ^v(\d+)\.(\d+)\.(\d+)$

conditions:
  dagger:
    name: Check latest Dagger release
    kind: githubrelease
    sourceid: dagger
    spec:
      owner: dagger
      repository: dagger
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      typefilter:
        release: true

targets:
  dagger:
    name: Update Dagger version in aqua.yaml
    kind: yaml
    transformers:
      - addprefix: "dagger/dagger@"
    spec:
      file: "aqua.yaml"
      key: "packages[1].name" # array access is limited to indices
```

The `targets.<yaml>.spec.key` syntax is currently limited to named keys and array indices. In addition, the challenge is not to modify pinned versions. (But this would probably have to be ensured by an additional condition)


##### updatecli diff --config updatecli.dagger.yaml
```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli.dagger.yaml"

SCM repository retrieved: 0


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



#############
# EXAMPLE 1 #
#############


SOURCES
=======

dagger
------
Searching for version matching pattern "^v(\\d+)\\.(\\d+)\\.(\\d+)$"
✔ Github Release version "v0.3.13" found matching pattern "^v(\\d+)\\.(\\d+)\\.(\\d+)$"


CHANGELOG:
----------

Release published on the 2023-02-24 18:06:22 +0000 UTC at the url https://github.com/dagger/dagger/releases/tag/v0.3.13

## Changelog

* :sparkles: Services, a.k.a. container-to-container networking by @vito in https://github.com/dagger/dagger/pull/4505
* :lock: Scrub secrets by @dolanor in https://github.com/dagger/dagger/pull/4518
* Initial support for remote cache config. by @sipsma in https://github.com/dagger/dagger/pull/4543
* Download runc binary instead of building it.  by @sipsma in https://github.com/dagger/dagger/pull/4559
* fix: remove workdir & configPath default values. by @TomChv in https://github.com/dagger/dagger/pull/4465
* Remove import dependency of CLI on containerd packages.  by @sipsma in https://github.com/dagger/dagger/pull/4562
* Use comma instead of semicolon for cache config separator. by @sipsma in https://github.com/dagger/dagger/pull/4563
* Disable logrus output only in CLI main. by @sipsma in https://github.com/dagger/dagger/pull/4572
* fix Directory.WithTimestamps with subdir by @vito in https://github.com/dagger/dagger/pull/4606
* docs: improve GraphQL with example and better format by @TomChv in https://github.com/dagger/dagger/pull/4367
* Get sha of the image after Container.From by @LokeshN in https://github.com/dagger/dagger/pull/4600
* Update buildkit to commit w/ cache exporter fix + nil panic fix by @sipsma in https://github.com/dagger/dagger/pull/4630
* Additive caching support for S3 backend by @sipsma in https://github.com/dagger/dagger/pull/4577

**Full Changelog**: https://github.com/dagger/dagger/compare/v0.3.12...v0.3.13

## What to do next?
- Read the [documentation](https://docs.dagger.io)
- Join our [Discord server](https://discord.gg/dagger-io)
- Follow us on [Twitter](https://twitter.com/dagger_io)



CONDITIONS:
===========

dagger
------
✔ Github Release version "v0.3.13" found


TARGETS
========

dagger
------

**Dry Run enabled**

⚠ Key 'packages[1].name', from file 'aqua.yaml', was updated from 'dagger/dagger@v0.3.12' to 'dagger/dagger@v0.3.13'

=============================

REPORTS:


⚠ Example 1:
        Source:
                ✔ [dagger] Get latest Dagger version from GitHub releases (kind: githubrelease)
        Condition:
                ✔ [dagger] Check latest Dagger release (kind: githubrelease)
        Target:
                ⚠ [dagger] Update Dagger version in aqua.yaml (kind: yaml)


Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
```
