### ISSUE TITLE
generate-registry: version_overrides is wrong

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1689]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 1.34.2 (9ed77af6753b936f7913034038a886a8f4e21333)
```

## Environment

* OS (Windows, Linux, macOS, etc):
* CPU Architecture (amd64, arm64, etc):

## How to reproduce

https://github.com/aquaproj/generate-registry-deep/actions/runs/4328416607

```yaml
packages:
  - type: github_release
    repo_owner: omegion
    repo_name: ssh-manager
    description: SSH Key Manager for 1Password, Bitwarden and AWS S3
    asset: ssh-manager-{{.OS}}-{{.Arch}}
    format: raw
    complete_windows_ext: false
    version_constraint: semver(">= 0.13.0")
    version_overrides:
      - version_constraint: semver(">= 0.11.0")
        supported_envs:
          - linux
          - darwin
      - version_constraint: semver(">= 0.10.0")
        supported_envs:
          - darwin/arm64
      - version_constraint: semver("< 0.10.0")
        supported_envs:
          - linux/arm64
```

The following version_overrides is wrong.

```yaml
      - version_constraint: semver(">= 0.10.0")
        supported_envs:
          - darwin/arm64
      - version_constraint: semver("< 0.10.0")
        supported_envs:
          - linux/arm64
```

## References

* https://github.com/aquaproj/generate-registry-deep/actions/runs/4328416607
* https://github.com/aquaproj/aqua-registry/pull/10404/commits/d7392523b99ef35a63c02586c4b888c9e47f41f8

**Comment by suzuki-shunsuke** [comment]
```console
$ aqua gr omegion/ssh-manager@v0.10.0
```

```yaml
packages:
  - type: github_release
    repo_owner: omegion
    repo_name: ssh-manager
    description: SSH Key Manager for 1Password, Bitwarden and AWS S3
    asset: ssh-manager-{{.OS}}-{{.Arch}}
    format: raw
    supported_envs:
      - linux/arm64
```

**Comment by suzuki-shunsuke** [comment]
```yaml
      - version_constraint: semver(">= 0.10.0")
        supported_envs:
          - darwin/arm64
```

🤔 darwin/arm64
