### ISSUE TITLE
Support deny policy

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1739]
## Feature Overview

Support deny policy.

## Why is the feature needed?

> Please explain the problem you want to solve.

To configure policy flexibly.
I assume the use case like forbidding some packages in Standard Registry.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```yaml
registries:
- type: standard
  ref: semver(">= 3.0.0")
packages:
- registry: standard
- deny: true
  registry: standard
  name: hashicorp/terraform
  version: semver("< 1.0.0")
  policy_id: forbid_terraform_v0
  description: |
    Terraform < v1 is forbidden. Please update.
```

Added some fields to packages.

- deny (boolean, default: false)
- policy_id: (string, default: ""): This must be unique or empty. This includes error message
- description: (string, default: ""): If this is set, this is outputted as error message
