### ISSUE TITLE
`go_install` package should ignore `asset`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1746]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 1.36.0 (3f31cf223d8968ee662fe2a06bc5a577958b7b10)
```

## Environment

* OS (Windows, Linux, macOS, etc):
* CPU Architecture (amd64, arm64, etc):

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

```yaml
# aqua.yaml

```

```console
$ 
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ 
```

## Actual Behaviour

https://github.com/aquaproj/aqua-registry/actions/runs/4417535453/jobs/7743385338

```
ERRO[0166] check file_src is correct                     aqua_version=1.36.0 env=linux/arm64 error="check file_src is correct: exe_path isn't found: stat /home/runner/.local/share/aquaproj-aqua/pkgs/go_install/github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier/v2.0.1/bin/slsa-verifier-{{.OS}}-{{.Arch}}: no such file or directory" file_name=slsa-verifier package_name=slsa-framework/slsa-verifier package_version=v2.0.1 program=aqua registry=standard
ERRO[0166] executable files aren't found
Files in the unarchived package:
slsa-verifier
   aqua_version=1.36.0 env=linux/arm64 package_name=slsa-framework/slsa-verifier package_version=v2.0.1 program=aqua registry=standard
```

```yaml
  - type: github_release
    repo_owner: slsa-framework
    repo_name: slsa-verifier
    description: Verify provenance from SLSA compliant builders
    asset: slsa-verifier-{{.OS}}-{{.Arch}}
    format: raw
    version_constraint: semver(">= 2.1.0")
    version_overrides:
      - version_constraint: semver(">= 2.0.0")
        type: go_install
        path: github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier
        # asset: slsa-verifier
        overrides:
          - goos: linux
            goarch: amd64
            type: github_release
            asset: slsa-verifier-{{.OS}}-{{.Arch}}
            format: raw

```

## References

*
