### ISSUE TITLE
Support omitting `{{.Format}}` in `Asset` and provide the variable `AssetWithoutExt`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1774]
## Feature Overview

Support omitting `{{.Format}}` in `Asset` and provide the variable `AssetWithoutExt`

## Why is the feature needed?

> Please explain the problem you want to solve.

To make the configuration simple.
This is useful when the format is changed from `raw` to `tar.gz` or something.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

### Example 1.

AS IS

```yaml
    asset: aks-engine-{{.Version}}-{{.OS}}-{{.Arch}}.tar.gz
    files:
      - name: aks-engine
        src: aks-engine-{{.Version}}-{{.OS}}-{{.Arch}}/aks-engine
```

TO BE

```yaml
    asset: aks-engine-{{.Version}}-{{.OS}}-{{.Arch}}
    format: tar.gz
    files:
      - name: aks-engine
        src: {{.AssetWithoutExt}}/aks-engine
```

### Example 2.

AS IS

```yaml
    asset: kalker-{{.OS}}.{{.Format}}
    format: zip
    overrides:
      - goos: linux
        format: raw
        asset: kalker-{{.OS}}
```

TO BE

```yaml
    asset: kalker-{{.OS}}
    format: zip
    overrides:
      - goos: linux
        format: raw
```

**Comment by suzuki-shunsuke** [comment]
- If `format` is set and the suffix of the rendered `asset` is different from `format`, add the suffix `format`
- Add the template variable `AssetWithoutExt`

```go
AssetWithoutExt := strings.TrimSuffix(asset, fmt.Sprintf(".%s", format))
```

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua-registry/issues/11365#issue-1661628006

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/pull/1862

**Comment by suzuki-shunsuke** [comment]
Hmm. This is a breaking change.

```
ERRO[0145] install the package                           aqua_version= env=darwin/arm64 error="the asset isn't found: btop-arm64-macos-monterey.tbz.tar.bz2" package_name=aristocratos/btop package_version=v1.2.12 program=aqua registry=standard
```

https://github.com/aquaproj/aqua-registry/blob/ac164cfd68015be9ea44deb5215f9260fe9ccbcf/pkgs/aristocratos/btop/registry.yaml

```yaml
packages:
  - type: github_release
    repo_owner: aristocratos
    repo_name: btop
    description: A monitor of resources
    asset: btop-{{.Arch}}-{{.OS}}.tbz
    format: tar.bz2
    supported_envs:
      - darwin
      - linux
    replacements:
      linux: linux-musl
      darwin: macos-monterey
      amd64: x86_64
    overrides:
      - goos: linux
        replacements:
          arm64: aarch64
    version_constraint: semver(">= 1.2.13")
    files:
      - name: btop
        src: btop/bin/btop
    version_overrides:
      - version_constraint: "true"
        files:
          - name: btop
            src: bin/btop
```
