### ISSUE TITLE
Support changing configuration by environment variable

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1804]
## Why is the feature needed?

> Please explain the problem you want to solve.

### Why not `AQUA_CONFIG`?

Benefits compared with `AQUA_CONFIG`

- You don't have to mind the configuration file path
- You can merge `aqua-checksums.json`

The issue of `AQUA_CONFIG` is about the checksum verification.
For example, in the following case aqua.yaml and aqua-dev.yaml share aqua-checksums.json.

```
aqua.yaml
aqua-dev.yaml
aqua-checksums.json
```

Then `update-checksum`'s `-prune` option removes the checksum for `aqua-dev.yaml`.

```
aqua update-checksum -prune
```

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ export AQUA_PROFILE=dev
```

Idea 1.

```yaml
registries:
  - type: standard
    ref: v3.149.0
packages:
  - import: imports/*.yaml
profiles:
  - name: dev
    import: aqua-dev.yaml
```

Idea 2.

```yaml
registries:
  - type: standard
    ref: v3.149.0
packages:
  - import: imports/*.yaml
  - import: aqua-dev.yaml
    profile: dev
```

Idea 3.

```yaml
registries:
  - type: standard
    ref: v3.149.0
packages:
  - import: imports/*.yaml
profiles:
  - name: dev
    registries: # If you omit `registries`, `registries` of default configuration is used.
      - type: standard
        ref: v3.149.0
    packages:
      - name: cli/cli@v2.0.0  
```

I think Idea 3 is good because aqua-renovate-config updates profile's registries and packages without additional configuration.
But we can also support Idea 1. Idea 1 is good for changing codeowner and CI's path filter.
