### ISSUE TITLE
aqua proxy might solve  managing pinned dockerized cli tools

### ISSUE THREAD

**Issue by sheldonhull** [aquaproj/aqua#1928]
This might be out of scope, but I thought it would be worth mentioning. 

If you look at a tool called Whalebrew it provided a cli experience to invoke dockerized commands. Despite my attempts to use it ended up being a bit more clunky than I'd like. There seem to be a lot of interest in the project in the past. I think those working with next to chains really like the idea of having tools that don't have static binaries contained in a docker image. For instance, the AWS cli required running python install commands and conflict between version one and two could occur. Using a docker image solves those concerns.

Let's say, a new package type got added to the aqua 
Toolchain that was `docker_command`. Maybe an additional feature could be a custom package in the yaml to invoke a dockerized command. 

You'd invoke your cli command that aqua proxy resolves since it was shimmed. 

Example... AWS cli isn't a single static binary. 

```
- name: aws-cli@v2.0
  registry: local
  args_docker_custom: []
  args_cli_custom: []
```

```
registry:
- name: aws-cli
  type: docker_command
  image: amazon/aws-cli:2.11.16
  args_docker_default:
    - '--rm'
  volume_mounts:
    - '${PWD}:/work'
    - '${HOME}/.aws:/home/nonroot/.aws:ro'
```

Anyway, this might not fit the project, but since part of the appeal of using dockerized commands, is that you can handle CLI tools that aren't static binaries wrapped up in that image it might be a future idea.  It would also let me use aqua to manage and pinned dockerized tools in the same wonderful experience I get through aqua. 

I'll refine as I get time as typed via mobile so sorry for any formatting issues. 😀
