### ISSUE TITLE
support setting the base directory path of `.files[].src` to simplify

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1985]
### Feature Overview

support setting the base directory path of `.files[].src`.

### Why is the feature needed?

To simplify the configuration.

### Does the feature include Breaking Changes?

No.

### Example Code

https://github.com/aquaproj/aqua-registry/blob/fafe10db475840269ca00c934cd34fcae2c8c9ad/pkgs/WebAssembly/binaryen/registry.yaml#L19-L43

AS IS

```yaml
files:
  - name: binaryen-unittests
    src: binaryen-{{.Version}}/bin/binaryen-unittests
  - name: wasm-as
    src: binaryen-{{.Version}}/bin/wasm-as
  - name: wasm-ctor-eval
    src: binaryen-{{.Version}}/bin/wasm-ctor-eval
  - name: wasm-dis
    src: binaryen-{{.Version}}/bin/wasm-dis
  - name: wasm-emscripten-finalize
    src: binaryen-{{.Version}}/bin/wasm-emscripten-finalize
```

TO BE

```yaml
files_dir: binaryen-{{.Version}}/bin
files:
  - name: binaryen-unittests
  - name: wasm-as
  - name: wasm-ctor-eval
  - name: wasm-dis
  - name: wasm-emscripten-finalize
```

### Reference

*
