### ISSUE TITLE
Allow to omit `.files[].name` if `.files[].src` is set

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#1986]
### Feature Overview

Allow to omit `.files[].name` if `.files[].src` is set.
If `.files[].src` is set, the default value of `.files[].name` is `filepath.Base(.Src)`

### Why is the feature needed?

To simplify.

### Does the feature include Breaking Changes?

No.

### Example Code

AS IS

```yaml
files:
  - name: binaryen-unittests
    src: binaryen-{{.Version}}/bin/binaryen-unittests
```

TO BE

```yaml
files:
  - src: binaryen-{{.Version}}/bin/binaryen-unittests
```

### Reference

*
