### ISSUE TITLE
Improve `generate-registry --deep`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2105]
### Feature Overview

Improve the output of `generate-registry --deep` command.

### Why is the feature needed?

Currently, sometimes `generate-registry --deep` outputs inconsistent and bad configuration.

Currently, `generate-registry --deep` generates a struct of Go from each version independently and compares them and generates version constraints.
But structs are inconsistent and can be changed per execution.

So I'd like to change the logic of `generate-registry --deep` drastically.

### Does the feature include Breaking Changes?

No.

### Example Code

```console
$ 
```

Configuration

```yaml

```

### Reference

- https://zenn.dev/shunsuke_suzuki/scraps/c2a186cf5178c0

**Comment by suzuki-shunsuke** [comment]
aqua v2.10.1

```
aqua-registry scaffold --deep caarlos0/fork-cleaner
```

```yaml
packages:
  - type: github_release
    repo_owner: caarlos0
    repo_name: fork-cleaner
    description: Quickly clean up unused forks on your github account
    asset: fork-cleaner_{{trimV .Version}}_{{.OS}}_all.{{.Format}}
    format: tar.gz
    overrides:
      - goos: linux
        asset: fork-cleaner_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
      - goos: windows
        format: zip
        asset: fork-cleaner_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
    rosetta2: true
    checksum:
      type: github_release
      asset: fork-cleaner_{{trimV .Version}}_checksums.txt
      algorithm: sha256
    version_constraint: semver(">= 2.3.0")
    version_overrides:
      - version_constraint: semver(">= 2.2.1")
        asset: fork-cleaner_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        overrides: []
        supported_envs:
          - linux
          - darwin
        rosetta2: false
      - version_constraint: semver(">= 2.2.0")
        asset: fork-cleaner_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        overrides: []
        supported_envs:
          - darwin
          - linux
          - amd64
        rosetta2: false
      - version_constraint: semver(">= 2.1.0")
        asset: fork-cleaner_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        overrides: []
        supported_envs:
          - darwin
          - linux
          - amd64
      - version_constraint: semver(">= 2.0.0")
        asset: fork-cleaner_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        overrides: []
        supported_envs:
          - linux
          - darwin
      - version_constraint: semver(">= 1.3.0")
        asset: fork-cleaner_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        overrides: []
        supported_envs:
          - linux/amd64
          - darwin
      - version_constraint: semver(">= 1.1.1")
        asset: fork-cleaner_{{.OS}}_{{.Arch}}.{{.Format}}
        overrides: []
        replacements:
          amd64: x86_64
          darwin: Darwin
          linux: Linux
        supported_envs:
          - linux/amd64
          - darwin
        checksum:
          type: github_release
          asset: fork-cleaner_checksums.txt
          algorithm: sha256
      - version_constraint: semver(">= 1.1.0")
        asset: fork-cleaner_{{.OS}}_{{.Arch}}.{{.Format}}
        overrides: []
        replacements:
          amd64: x86_64
          darwin: Darwin
          linux: Linux
        supported_envs:
          - linux/amd64
          - darwin
        checksum:
          type: github_release
          asset: fork-cleaner_{{.OS}}_{{.Arch}}.tar.gz.checksums
          algorithm: sha256
      - version_constraint: semver("< 1.1.0")
        asset: fork-cleaner_{{.OS}}_{{.Arch}}.{{.Format}}
        overrides: []
        replacements:
          amd64: x86_64
          darwin: Darwin
          linux: Linux
        supported_envs:
          - linux/amd64
          - darwin
        checksum:
          enabled: false
```

**Comment by suzuki-shunsuke** [comment]
```
aqua -v
aqua version 2.10.2-1 (cc430f328833dfffdd425f3a48cb7914e5abb3f1)
```

```
aqua-registry scaffold --deep kyverno/kyverno
```

```yaml
packages:
  - type: github_release
    repo_owner: kyverno
    repo_name: kyverno
    description: Kubernetes Native Policy Management
    asset: kyverno-cli_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
    format: tar.gz
    overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x86_64
    supported_envs:
      - darwin
      - linux
      - amd64
    checksum:
      type: github_release
      asset: checksums.txt
      algorithm: sha256
    version_constraint: semver(">= 1.10.1-rc.1")
    version_overrides:
      - version_constraint: semver(">= 1.6.0-rc1")
      - version_constraint: semver(">= 1.4.2-rc4")
        supported_envs:
          - darwin
          - amd64
        rosetta2: true
      - version_constraint: semver(">= 1.4.2-rc3")
        overrides: []
        supported_envs:
          - linux/amd64
        checksum:
          enabled: false
      - version_constraint: semver(">= 1.1.6-rc5")
        supported_envs:
          - darwin
          - amd64
        rosetta2: true
      - version_constraint: semver("< 1.1.6-rc5")
        asset: kyverno_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        rosetta2: true
```

**Comment by suzuki-shunsuke** [comment]
```
aqua gr --deep apache/camel-k
```

```yaml
packages:
  - type: github_release
    repo_owner: apache
    repo_name: camel-k
    description: Apache Camel K is a lightweight integration platform, born on Kubernetes, with serverless superpowers
    asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
    format: tar.gz
    supported_envs:
      - darwin
      - linux
      - amd64
    version_constraint: semver(">= 2.0.0")
    version_overrides:
      - version_constraint: semver(">= 2.0.0-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
      - version_constraint: semver(">= 1.12.2-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.12.1")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.12.1-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.12.0")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.11.2-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.11.1")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.11.0")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.11.0")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.5-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.4")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.4-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.3")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.3-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.2")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.2-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.1")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.1-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.10.0")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.9.3-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.9.2")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.9.2-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.9.1")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.9.1-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.9.0")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.9.0-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
        rosetta2: true
      - version_constraint: semver(">= 1.8.3-nightly")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.6.1")
        overrides:
          - goos: darwin
            goarch: arm64
            asset: camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}bit.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
      - version_constraint: semver(">= 1.1.0")
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
        rosetta2: true
      - version_constraint: semver(">= 1.0.0-M1")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
        rosetta2: true
      - version_constraint: semver(">= 0.3.4")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
        rosetta2: true
        checksum:
          type: github_release
          asset: "{{.Asset}}.sha512"
          algorithm: sha512
      - version_constraint: semver("< 0.3.4")
        asset: camel-k-client-{{.Version}}-{{.OS}}-{{.Arch}}.{{.Format}}
        replacements:
          amd64: 64bit
          darwin: mac
        supported_envs:
          - darwin
          - amd64
        rosetta2: true
```
