### ISSUE TITLE
When installing `snaplet/cli`, it doesn't include the default version from `snaplet/cli/pkg.yaml`

### ISSUE THREAD

**Issue by Gowiem** [aquaproj/aqua#2130]
## package name

`snaplet/cli`

## aqua version

> aqua version 2.10.1 (fbf3b157b21897fa2f315fbc30474acafded108d)

## Environment

- MacOS
- arm64

## How to reproduce

1. `aqua init`
2. `aqua g -i snaplet/cli`

## Expected Behavior

I would expect the above commands would grab the `0.54.3` version specified here: https://github.com/aquaproj/aqua-registry/blob/main/pkgs/snaplet/cli/pkg.yaml#L2

## Actual Behavior

It updates `aqua.yaml` to the following:

```yaml
---
# aqua - Declarative CLI Version Manager
registries:
- type: standard
  ref: v4.30.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: snaplet/cli
  version: "[SET PACKAGE VERSION]"
```
