### ISSUE TITLE
Support tools that don't have versions

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2133]
### Feature Overview

This issue came from here.

- https://github.com/aquaproj/aqua-registry/issues/13989

Support tools that don't have versions.

### Why is the feature needed?

Some tools doesn't have versions.

For example, trunk is expected to install a wrapper script in `PATH`, but this script doesn't have versions.

https://get.trunk.io

aqua assumes that packages have versions for now, so aqua doesn't support these tools officially.
Of course you can install these tools by custom Registries, but standard Registry doesn't accept these tools.

The issue of these tools is that even if these tools are updated aqua can't update them.
We also consider the checksum verification.

### Workaround

There are two workarounds.

1. Install these tools by custom Registries
2. Install these tools outside of aqua

Custom Registries require Policy, so it's a little bothersome.

2 is the recommendation way for now, but I understand users aren't satisfied.
It's ideal to manage tools by aqua as much as possible.

### Example Code

```yaml
packages:
  - type: http
    name: trunk-io/cli-wrapper
    url: https://get.trunk.io
    versioning: false # New field
    format: raw
    files:
      - name: trunk
    supported_envs:
      - darwin
      - amd64
```

Added a new filed `versioning`, but I'm not sure if this field is really necessary.

### Reference

- https://github.com/aquaproj/aqua-registry/issues/13989
