### ISSUE TITLE
Support `profile`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#228]
```
~/.aqua/config/
  current_profile.json
  profile.yaml
```

```json
{
  "profile": "service-a"
}
```

```yaml
profiles:
- name: service-a
  description: "For Service A"
  configs:
  - path: service-a.yaml
```

```
export AQUA_PROFILE=service-a
```

```
$ aqua profile set service-a
```

```
$ aqua profile unset
```

```
$ aqua profile list
```
