### ISSUE TITLE
Support `envs` in `overrides` instead of `goos` and `goarch`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2318]
### Feature Overview

Add a new field `envs` to `overrides`.
The syntax of `envs` is same with `supported_envs`.

### Why is the feature needed?

The syntax of `supported_envs` is more flexible than the combination of `goos` and `goarch`.
In some cases we can simplify the code.

For example, the combination of `goos` and `goarch` can't express the pair of `linux/arm64` and `windows/arm64`.

```yaml
overrides:
  - goos: windows
    goarch: arm64
    # ...
  - goos: linux
    goarch: arm64
    # ...
```

`envs` can simplify the code.

```yaml
overrides:
  - envs:
      - windows/arm64
      - linux/arm64
    # ...
```

### Workaround

Use `goos` and `goarch`.
