### ISSUE TITLE
Support changing slsa-verifier's options

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2392]
### Feature Overview

Support changing slsa-verifier's command line options.

https://aquaproj.github.io/docs/reference/registry-config/slsa-provenance/

### Why is the feature needed?

Some packages don't support `--source-tag`.

- https://github.com/xeol-io/xeol/issues/210

Currently, options are static.

https://github.com/aquaproj/aqua/blob/70f84d66ba9af98008360fd7b846094f020b4c6f/pkg/slsa/exec.go#L73-L82

### Workaround

If `--source-tag` isn't supported, we need to disable `slsa_provenance`, but this isn't desirable.

### Example Code

registry.yaml

```yaml
slsa_provenance:
  opts:
    - --source-uri
    - https://github.com/<foo>/<bar>
    - --source-tag
    - {{.Version}}
```
