### ISSUE TITLE
generate-registry: Improve the structure of version_overrides

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2425]
### Feature Overview

Improve the structure of `version_overrides`.

Before

```yaml
packages:
  - type: github_release
    repo_owner: Azure
    repo_name: aztfexport
    asset: aztfexport_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
    format: zip
    version_constraint: semver(">= 0.11.0")
    version_overrides:
      - version_constraint: semver(">= 0.7.0")
        asset: aztfy_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
      - version_constraint: semver(">= 0.6.0")
        asset: aztfy_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        format: tar.gz
      - version_constraint: semver("< 0.6.0")
        supported_envs:
          - linux
```

After

```yaml
packages:
  - type: github_release
    repo_owner: Azure
    repo_name: aztfexport
    version_constraint: "false"
    version_overrides:
      - version_constraint: semver("<= 0.5.0")
        asset: aztfexport_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        format: zip
        supported_envs:
          - linux
      - version_constraint: semver("<= 0.6.0")
        asset: aztfy_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        format: tar.gz
      - version_constraint: semver("<= 0.10.0")
        asset: aztfy_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        format: zip
      - version_constraint: "true"
        asset: aztfexport_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
        format: zip
```

### Why is the feature needed?

The current structure of version_overrides has an issue that it's difficult to update the setting because if the setting of the latest version is changed we need to fix the setting of old versions too.

To resolve the issue, we stop merging settings by `version_overrides`.
If the setting of the latest versions is changed, we only have to fix the last `version_override`.
