### ISSUE TITLE
Add option to override existing package on `aqua g -i` command

### ISSUE THREAD

**Issue by ponkio-o** [aquaproj/aqua#2722]
### Feature Overview

I want feature to override existing package in `aqua.yaml`. I often face opportunity when I want to switch the version of cli tool managed by aqua.

### Why is the feature needed?

Because I have to take many step when I want to switch the version.

1. Open the `aqua.yaml`
2. Remove the package (e.g. `- name: cli/cli@v1.0.0`)
3. I run the `aqua g -i -s`

I propose the new option in to the `aqua g -i`. For example, `aqua g -i -f (--force)`.
(But aqua generate command has already `-f` option 😂)

### Workaround

Nothing in particular

### Example Code

```console
$ aqua g -i -s
<select the ysugimoto/falco@1.3.0>
WARN[0003] same package already exists                   aqua_version=2.15.0 env=darwin/arm64 package_name=ysugimoto/falco@v1.3.0 package_registry=standard program=aqua
```

Configuration

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
  - type: standard
    ref: v4.147.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: ysugimoto/falco@v0.24.0
```
