### ISSUE TITLE
Support getting Go version from go.mod

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2730]
### Feature Overview

Support getting Go version from go.mod.

### Why is the feature needed?

- https://github.com/orgs/aquaproj/discussions/2609

### Workaround

https://github.com/orgs/aquaproj/discussions/2609#discussioncomment-8066245

> One of the workarounds is to update toolchain and go in aqua.yaml at the same time by Renovate's grouping feature.
> https://docs.renovatebot.com/configuration-options/#group

### Example Code

```yaml
packages:
  - name: golang/go
    go_version_file: go.mod
```

**Comment by suzuki-shunsuke** [comment]
https://github.com/actions/setup-go/blob/4ab57d7ea2fd0c9948210b2e0784e280674e7144/src/installer.ts#L420-L432

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua/pull/2632

**Comment by suzuki-shunsuke** [comment]
We can make this feature more general.

```yaml
packages:
  - name: golang/go
    version_file: go.mod
    version_file_pattern: "(?m)^go (\d+\.\d+.\d+)$"
    version_file_pattern_type: regexp
```
