### ISSUE TITLE
Support verifying packages with minisign

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#2978]
### Feature Overview

Support verifying packages with [minisign](https://github.com/jedisct1/minisign).

### Why is the feature needed?

To install some packages securely.
For example, [zig](https://ziglang.org/download/) is signed by minisign.

### Example Code

This feature is similar to Cosign and slsa-verifier.

https://aquaproj.github.io/docs/reference/registry-config/cosign/

This feature depends on minisign.
So aqua should install minisign transparently same as Cosign and slsa-verifier.

registry.yaml

```yaml
minisign:
  enabled: true
  public_key: "RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U"
  # public_key_url: https://example/signature.pub
```

### Note

- https://github.com/aquaproj/aqua/issues/2665#issuecomment-2202692592
