### ISSUE TITLE
Use local registry from any of the files in the configuration path

### ISSUE THREAD

**Issue by W1M0R** [aquaproj/aqua#3016]
### Feature Overview

The configuration search order is specified here: https://aquaproj.github.io/docs/reference/config/#configuration-file-path

Consider the following monorepo setup:

```pwsh
❯ aqua info
{
  "version": "2.30.0",
  "commit_hash": "22e2139d9200c1619914bafed680db2cfe39a354",
  "os": "windows",
  "arch": "amd64",
  "pwd": "C:\\Users\\(USER)\\monorepo\\src\\proj1",
  "root_dir": "C:\\Users\\(USER)\\AppData\\Local\\aquaproj-aqua",
  "env": {
    "AQUA_DISABLE_POLICY": "true",
    "AQUA_PROGRESS_BAR": "true",
    "AQUA_ROOT_DIR": "C:\\Users\\(USER)\\AppData\\Local\\aquaproj-aqua"
  },
  "config_files": [
    {
      "path": "C:\\Users\\(USER)\\monorepo\\src\\proj1\\.aqua\\aqua.yaml"
    },
    {
      "path": "C:\\Users\\(USER)\\monorepo\\.aqua\\aqua.yaml"
    }
  ]
}
```

If I am in `proj1` and run the `aqua i -l` command, it should create shims for all packages found in the list of configuration files.

The aqua.yaml file in the root of the repository looks like this:

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.204.0  # renovate: depName=aquaproj/aqua-registry
- name: local
  type: local
  path: aqua-registry.yaml # Relative path from aqua.yaml
packages:
- name: github.com/stefanlogue/meteor@v0.22.0
  registry: local
```

And the `aqua-registry.yaml` in the root of the monorepo looks like this:

```yaml
packages:
  - type: go_install
    path: github.com/stefanlogue/meteor
    description: A highly configurable CLI tool for writing conventional commits
    version_source: github_tag
  - type: go_install
    path: github.com/wailsapp/wails/v2/cmd/wails
    description: Create beautiful applications using Go
    version_source: github_tag
```

The `aqua.yaml` for `proj1` is:

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.204.0  # renovate: depName=aquaproj/aqua-registry
packages:
- name: github.com/wailsapp/wails/v2/cmd/wails@v2.9.1
  registry: local
```

An `aqua i -l` in `proj1` should result in two packages being installed: `meteor` and `wails`. However, the following error occurs:

```pwsh
❯ aqua i -l
ERRO[0000] install the package                           aqua_version=2.30.0 env=windows/amd64 error="registry isn't found" package_name=github.com/wailsapp/wails/v2/cmd/wails package_version=v2.9.1 program=aqua registry=local
```

Ideally, since aqua knows about the list of configuration files (via `aqua info`), instead of "registry isn't found", it should try and find the registry in one of the other configuration files (i.e. the root configuration), and then try again with the installation.

### Why is the feature needed?

In a monorepo, it would make sense to have a local registry specified once in the root of the monorepo, that can be used by other projects in the monorepo. The workarounds are good enough, but I think the experience can be improved.

### Workaround

A few workarounds exist:

1. Put the shared registry file somewhere in $HOME and reference it explicitly
2. Keep the shared registry file in the root of the repo and reference it explicitly using a relative path
3. Create a copy of the shared registry file for every project and reference it explicitly

Example `aqua.yaml`:

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.204.0  # renovate: depName=aquaproj/aqua-registry
- name: local
  type: local
  path: ../../../aqua-registry.yaml # the project knows where the root registry file is (moving the project around will require updating of this path)
  path: $HOME/aqua-registry-monorepo.yaml # a build step copies the root aqua-registry file to $HOME
  path: aqua-registry-copy.yaml # a build step copies the root aqua-registry file to here
packages:
...
```

### Example Code

```console
$ aqua i -l
```

Configuration

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.204.0  # renovate: depName=aquaproj/aqua-registry
packages:
- name: github.com/wailsapp/wails/v2/cmd/wails@v2.9.1
  registry: local # local is specified in the root aqua yaml file
```
