### ISSUE TITLE
Verify checksum file with minisign

### ISSUE THREAD

**Issue by sapphi-red** [aquaproj/aqua#3072]
### Feature Overview

Support for verifying a checksum file with minisign.

### Why is the feature needed?

#2994 added support for [verifying an artifact](https://github.com/aquaproj/aqua/blob/31c19916607ff5ced955463fc075551a6b8ef459/pkg/minisign/exec.go#L71) with minisign. [bufbuild/buf](https://github.com/bufbuild/buf) uses minisign to generate a signature, but for a checksum file instead of an artifact.

- https://buf.build/docs/installation > "GitHub" tab > "Verifying a release"

### Example Code

An example how to use this feature in the registry config:

- Add `minisign` option under `checksum` like `cosign`:
  ```yaml
  checksum:
    type: github_release
    asset: sha256.txt
    algorithm: sha256
    minisign:
      type: github_release
      asset: sha256.txt.minisig
      public_key: RWQ/i9xseZwBVE7pEniCNjlNOeeyp4BQgdZDLQcAohxEAH5Uj5DEKjv6
  ```
- or, add `target` option under `minisign` option:
  ```yaml
  minisign:
    target: checksum
    type: github_release
    asset: sha256.txt.minisig
    public_key: RWQ/i9xseZwBVE7pEniCNjlNOeeyp4BQgdZDLQcAohxEAH5Uj5DEKjv6
  ```

Not sure which one is better.
