### ISSUE TITLE
Specify public key for minisign by URL or asset file name in GitHub Releases

### ISSUE THREAD

**Issue by sapphi-red** [aquaproj/aqua#3073]
### Feature Overview

Support specifying public key for minisign by URL or asset file name in GitHub Releases like `public_key_url` written in #2978.

### Why is the feature needed?

https://github.com/aquaproj/aqua/pull/2994 added support for verifying with minisign. [cargo-bins/cargo-binstall](https://github.com/cargo-bins/cargo-binstall) signs the artifacts using minisign with an ephemeral key and uploads the generated public key for every release. This means it's not possible to use `public_key` option, which is a static value.

https://github.com/cargo-bins/cargo-binstall/releases/tag/v1.4.1#:~:text=We%20use%20a%20just%2Din%2Dtime%20ephemeral%20key%20or%20%22keyless%22%20setup%20which%20generates%20a%20brand%20new%20signing%20key%20for%20every%20release.

[The v2.31.0 release post's example code](https://github.com/aquaproj/aqua/releases/tag/v2.31.0#:~:text=public_key_url%3A%20https%3A//example/signature.pub) includes `public_key_url` option, but it seems it doesn't work and wasn't implemented by #2994 if I'm not missing anything. At least,  [the json schema in the PR](https://github.com/aquaproj/aqua/pull/2994/files#diff-96792e134f0f1a9ded5b771971cad9e17a9b4fe1e57625d7330f58350b5d750cR242-R266) doesn't include that option.

### Example Code

An example how to use this feature in the registry config:

```yaml
minisign:
  type: github_release
  asset: cargo-binstall-{{.Arch}}-{{.OS}}.{{.Format}}.sig
  public_key:
    type: github_release
    asset: minisign.pub
```
```yaml
minisign:
  type: github_release
  asset: cargo-binstall-{{.Arch}}-{{.OS}}.{{.Format}}.sig
  public_key:
    type: http
    url: https://github.com/cargo-bins/cargo-binstall/releases/download/v{{.Version}}/minisign.pub
```
