### ISSUE TITLE
Verify packages using GitHub Artifact Attestations

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#3118]
### Feature Overview

- https://github.com/aquaproj/aqua/issues/2972
- https://github.com/aquaproj/aqua/issues/3117
- https://github.blog/changelog/2024-06-25-artifact-attestations-is-generally-available/
- https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds

Verify packages using GitHub Artifact Attestations.

### Why is the feature needed?

To install packages securely.

### Example Code

Similar to Cosign and SLSA Provenance.

https://aquaproj.github.io/docs/reference/security/cosign-slsa

```yaml
packages:
  - type: github_release
    repo_owner: terraform-linters
    repo_name: tflint
    asset: tflint_{{.OS}}_{{.Arch}}.{{.Format}}
    format: zip
    github_artifact_attestations:
      signer-workflow: terraform-linters/tflint/.github/workflows/release.yml
```

### Note

- https://zenn.dev/shunsuke_suzuki/scraps/4809dd473addf9
