### ISSUE TITLE
Enhance version fetching and support nightly versions

### ISSUE THREAD

**Issue by mpal9000** [aquaproj/aqua#3198]
### Feature Overview

Currently there is no way to handle interactively (select, update, remove, etc.) non released "nightly" versions.

### Why is the feature needed?

Maybe if aqua could support a new `json` value for `version_source` attribute, in order to declare how to fetch and parse (e.g. https://github.com/itchyny/gojq) the available versions, we would be able to declare how to fetch all "nightly" and "release" versions. And then work with those interactively via the CLI, like searching and selecting them, using `aqua g -s`.

### Example Code

Configuration

e.g. for Zig:

```yaml
version_source: json
  # - file: versions.json # or a local file
  - url: https://ziglang.org/download/index.json
    query: "(keys | del(.[] | select(. == "master"))), [.master.version] | .[]"
```

or for Node.js:

```yaml
version_source: json
  - url: https://nodejs.org/download/release/index.json
    query: "[.[].version]"
  - url: https://nodejs.org/download/nightly/index.json
    query: "[.[].version]"
```
