### ISSUE TITLE
Allow to set command aliases in aqua.yaml

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#3223]
### Feature Overview

Allows you to execute commands by different names.

### Why is the feature needed?

You can run a same package with different versions in the same aqua.yaml.
You can also implement a wrapper of a specific command.

### Workaround

https://github.com/suzuki-shunsuke/example-wrapper

### Example Code

aqua.yaml

```yaml
registries:
- type: standard
  ref: v4.246.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: hashicorp/terraform@v1.9.8
- name: hashicorp/terraform
  version: v0.13.7
  command_aliases:
    - command: terraform
      alias: terraform-013
```

wrapper:

```yaml
packages:
- name: suzuki-shunsuke/example-wrapper@v1.0.0 # The wrapper of Terraform
- name: hashicorp/terraform@v1.9.8
  command_aliases:
    - command: terraform
      alias: terraform-core
      no_link: true # Stop creating a symbolic link. You can still execute the command via `aqua exec -- terraform-core`.
```
