### ISSUE TITLE
`aqua g -i` removes comments in array (packages)

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#3323]
### aqua info

```console
$ aqua info
{
  "version": "2.38.2",
  "commit_hash": "ae397291f7ee7f5fd3559a123f7a7edf743720df",
  "os": "darwin",
  "arch": "arm64",
  "pwd": "/Users/(USER)/test/aqua/comment",
  "root_dir": "/Users/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "AQUA_PROGRESS_BAR": "true",
    "GITHUB_TOKEN": "(masked)"
  },
  "config_files": [
    {
      "path": "/Users/(USER)/test/aqua/comment/aqua.yaml"
    }
  ]
}
```

### Overview

`aqua g -i` removes comments in array (packages).

### How to reproduce

aqua.yaml

```yaml
registries:
- type: standard
  ref: v4.267.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: suzuki-shunsuke/mkghtag@v0.1.4
# hello
- name: suzuki-shunsuke/tfcmt@v4.14.0
```

Executed command and output

```sh
aqua g -i suzuki-shunsuke/ghalint
```

### Expected behaviour

Comments in packages are kept.

```
registries:
- type: standard
  ref: v4.267.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: suzuki-shunsuke/mkghtag@v0.1.4
# hello
- name: suzuki-shunsuke/tfcmt@v4.14.0
- name: suzuki-shunsuke/ghalint@v1.0.0
```

### Actual behaviour

Comments in packages are removed.

```yaml
registries:
- type: standard
  ref: v4.267.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: suzuki-shunsuke/mkghtag@v0.1.4
- name: suzuki-shunsuke/tfcmt@v4.14.0
- name: suzuki-shunsuke/ghalint@v1.0.0
```

### Note

I created this issue on https://github.com/goccy/go-yaml/issues/502 , got an answer.

- https://github.com/goccy/go-yaml/issues/502#issuecomment-2515981600

Probably we can solve this issue.
