### ISSUE TITLE
`aqua gr` generates arm64 replacements even though windows_arm_emulation is enabled

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#3336]
### aqua info

```console
$ aqua info
{
  "version": "2.38.3",
  "commit_hash": "53d9f3361b6b64e36d06689524a96e0048a348db",
  "os": "darwin",
  "arch": "arm64",
  "pwd": "/Users/(USER)/Documents/aqua/aqua",
  "root_dir": "/Users/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "AQUA_GLOBAL_CONFIG": ":/Users/(USER)/repos/src/github.com/aquaproj/aqua-registry/aqua-all.yaml",
    "AQUA_PROGRESS_BAR": "true"
  },
  "config_files": [
    {
      "path": "/Users/(USER)/Documents/aqua/aqua/aqua/aqua.yaml"
    }
  ]
}
```

### Overview

`aqua gr` generates arm64 replacements even though windows_arm_emulation is enabled.

### How to reproduce

```sh
aqua gr -l 1 coder3101/protols
```

### Expected behaviour

```yaml
packages:
  - type: github_release
    repo_owner: coder3101
    repo_name: protols
    description: Language Server for protocol buffers
    asset: protols-{{.Arch}}-{{.OS}}.{{.Format}}
    format: tar.gz
    windows_arm_emulation: true
    overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x86_64
      arm64: aarch64
      darwin: apple-darwin
      linux: unknown-linux-gnu
      windows: pc-windows-msvc
```

### Actual behaviour

```yaml
packages:
  - type: github_release
    repo_owner: coder3101
    repo_name: protols
    description: Language Server for protocol buffers
    asset: protols-{{.Arch}}-{{.OS}}.{{.Format}}
    format: tar.gz
    windows_arm_emulation: true
    overrides:
      - goos: windows
        format: zip
        replacements:
          arm64: arm64
    replacements:
      amd64: x86_64
      arm64: aarch64
      darwin: apple-darwin
      linux: unknown-linux-gnu
      windows: pc-windows-msvc
```

### Note

We can reproduce the issue using old aqua (v2.30.0) too.

```sh
aqua upa v2.30.0
```

---

- https://github.com/aquaproj/aqua-registry/pull/29527
