### ISSUE TITLE
Get version of specific package in aqua.yaml config

### ISSUE THREAD

**Issue by SanderKnape** [aquaproj/aqua#3464]
### Feature Overview

I'm looking for an easy way to get a configured version in the aqua.yaml for a specific package.

### Why is the feature needed?

In some cases I don't want to use Aqua to install a package, but I'd like to treat the aqua.yaml as the "single source of truth" for which package versions I want installed.

More specifically: I'm using [tflint](https://github.com/terraform-linters/tflint) in GitHub Actions and I want to use the [setup-tflint](https://github.com/terraform-linters/setup-tflint) action for installing tflint (instead of aqua) as that action also sets up the [problem matcher](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md). I do want to use the version configured in the aqua.yaml so that we use the same version locally.

Right now the following works, but it's not great:

```
- run: echo "TFLINT_VERSION=$(yq '.packages[] | select(.name | contains("tflint")) | .name | split("@")[1]' aqua.yaml)" >> $GITHUB_ENV
- uses: terraform-linters/setup-tflint@v4
  with:
    tflint_version: ${{ env.TFLINT_VERSION }}
```

### Example Code

There's a few ways this could be implemented.

```
$ aqua list -installed --format json
{
  "terraform-linters/tflint": "v0.55.0"
}
```

Add a (global) config option to return JSON to make it easier to grab the version.

Or add a more specific command that outputs the version.
