### ISSUE TITLE
Support wildcard registry repository names in aqua-policy

### ISSUE THREAD

**Issue by SanderKnape** [aquaproj/aqua#3484]
### Feature Overview

I'd like to allow all registries in our private GitHub Organization in a policy file.

### Why is the feature needed?

We have many repositories and various internal tools that we want to use in these repositories using Aqua. Right now, we'd have to add the registry for each tool/repository in each repository that uses those tools. We also have to keep those files up to date.

Instead it would be great if we can just allow all internal tools coming from our GitHub Organization.

### Example Code

Something like the following:

aqua_policy.yaml
```yaml
registries:
  - type: standard
  - name: "*" # or just no name
     type: github_content
     repo_owner: OrganizationName
```

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
I don't understand your request well.

You can manage a private registry in a repository like `<your org>/aqua-registry`,
and you can install tools by adding the following policy file in repositories:

aqua-policy.yaml:

```yaml
registries:
  - name: private
    type: github_content
    repo_owner: your-org
    repo_name: aqua-registry
    path: registry.yaml
packages:
  - registry: private
```

aqua.yaml:

```yaml
registries:
- name: private
  type: github_content
  repo_owner: your-org
  repo_name: aqua-registry
  path: registry.yaml
  ref: v1.0.0
packages:
- name: your-org/foo@v1.0.0
  registry: private
```

Does it make sense?

> we'd have to add the registry for each tool/repository in each repository that uses those tools.

You don't have to add registry.yaml in each tool repository.
You only need to manage a single registry.
