### ISSUE TITLE
Support `version_source`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#349]
## AS IS

```yaml
- name: hashicorp/consul
  type: http
  url: 'https://releases.hashicorp.com/consul/{{trimV .Version}}/consul_{{trimV .Version}}_{{.OS}}_{{.Arch}}.zip'
  link: https://www.consul.io/
  description: Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure
  files:
  - name: consul
```

```console
$ echo standard,hashicorp/consul | aqua g -f -
- name: hashicorp/consul
  version: '[SET PACKAGE VERSION]'
```

## TO BE

```yaml
# omit `name` and `files`
- type: http
  version_source: github_release
  repo_owner: hashicorp
  repo_name: consul
  url: 'https://releases.hashicorp.com/consul/{{trimV .Version}}/consul_{{trimV .Version}}_{{.OS}}_{{.Arch}}.zip'
  link: https://www.consul.io/
  description: Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure
```

```console
$ echo standard,hashicorp/consul | aqua g -f -
- name: hashicorp/consul@v1.10.3
```
