### ISSUE TITLE
Support generate-registry configuration file

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#3561]
### Feature Overview

Support generate-registry configuration file.

### Why is the feature needed?

To configure generate-registry flexibly.

### Example Code

```console
$ aqua gr -c generate.yaml <package name>
```

Configuration

```yaml
limit: 0
test_data: pkg.yaml
files:
  - name: foo
excluded_version_regexp: # Regular expression
  - -dev$
excluded_versions: # https://expr-lang.org/docs/language-definition
  - semver("< 1.0.0")
excluded_assets:
  - -dev # regular expression
```
