### ISSUE TITLE
`aqua gr` sets `complete_windows_ext: false` wrongly

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#3565]
### aqua info

```console
$ aqua info
{
  "version": "2.45.0-0",
  "commit_hash": "c6f675f804718569d3bfc8b9cbb2455937f62b2b",
  "os": "darwin",
  "arch": "arm64",
  "pwd": "/Users/(USER)/Documents/aqua/aqua",
  "root_dir": "/Users/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "AQUA_GLOBAL_CONFIG": ":/Users/(USER)/repos/src/github.com/aquaproj/aqua-registry/aqua-all.yaml:/Users/(USER)/repos/src/github.com/aquaproj/aqua-registry/aqua-all.yaml",
    "AQUA_PROGRESS_BAR": "true"
  },
  "config_files": [
    {
      "path": "/Users/(USER)/Documents/aqua/aqua/aqua/aqua.yaml"
    }
  ]
}
```

### Overview

`aqua gr` sets `complete_windows_ext: false` wrongly.

### How to reproduce

```sh
aqua gr -l 1 arch-go/arch-go
```

### Expected behaviour

`complete_windows_ext: false` isn't set.

### Actual behaviour

`complete_windows_ext: false` is set.

```yaml
packages:
  - type: github_release
    repo_owner: arch-go
    repo_name: arch-go
    description: Architecture checks for Go projects
    asset: arch-go_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
    format: tar.gz
    windows_arm_emulation: true
    complete_windows_ext: false
    overrides:
      - goos: windows
        format: zip
    checksum:
      type: github_release
      asset: arch-go_{{.Version}}_checksums.txt
      algorithm: sha256
```
