### ISSUE TITLE
Support for Installing protoc-gen-go-grpc on ARM64

### ISSUE THREAD

**Issue by mnagaa** [aquaproj/aqua#3651]
### Feature Overview

Enable installation of protoc-gen-go-grpc on ARM64 architecture.

### Why is the feature needed?

I am using an ARM64 CPU and attempted to install `protoc-gen-go-grpc` within a devcontainer. However, the installation skipped. By copying the package to the local registry and adding `arm64` to the `supported_envs`, the installation succeeded and functioned correctly.

### Example Code

https://github.com/aquaproj/aqua-registry/blob/main/pkgs/grpc/grpc-go/protoc-gen-go-grpc/registry.yaml 

```yaml
  - name: grpc/grpc-go/protoc-gen-go-grpc
    type: github_release
    repo_owner: grpc
    repo_name: grpc-go
    description: Generate Go language bindings of services in protobuf definition files for gRPC
    asset: 'protoc-gen-go-grpc.{{trimPrefix "cmd/protoc-gen-go-grpc/" .Version}}.{{.OS}}.{{.Arch}}.tar.gz'
    supported_envs:
      - darwin
      - amd64
      - arm64 # add this line
    version_filter: 'Version startsWith "cmd/protoc-gen-go-grpc/"'
    rosetta2: true
    files:
      - name: protoc-gen-go-grpc
```
