### ISSUE TITLE
Support for verifying executables within archives

### ISSUE THREAD

**Issue by scop** [aquaproj/aqua#3754]
### Feature Overview

Would be nice to have support for verifying signatures/provenance for executables coming from inside archives. Currently it seems aqua can verify only the downloaded assets as-is.

### Why is the feature needed?

Example case in https://github.com/kubewarden/kwctl: GH artifact attestations are generated, but only for executables that are put within archives, not the archives themselves.
* https://github.com/kubewarden/kwctl/blob/2dbab69752a2447a1dac767e17596246d5816b10/.github/workflows/build.yml
* https://github.com/kubewarden/kwctl/releases/tag/v1.23.0
* https://github.com/kubewarden/kwctl/attestations

This practice is not that widespread at the moment at least with GH attestations I believe (kwctl is the first I met it with), but coincidentally I happened to think of it being a good practice already some time ago: it enables re-verification of already installed binaries afterwards.

I suppose this would be applicable at least some other signing/provenance types besides GH attestations as well.

### Example Code

Configuration

```yaml
# maybe files could be used/extended for this?
    files:
      - name: example
        github_artifact_attestations:
          signer_workflow: ...
```
