### ISSUE TITLE
Registry in the package repository

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#419]
## Problem to solve

When the package definition is changed, the package maintainer have to update the standard registry.
Ideally, the registry should be managed in the same repository.

You can define the registry in the same repository.

aqua-registry.yaml

```yaml
packages:
- type: github_release
  repo_owner: suzuki-shunsuke
  repo_name: foo
  asset: 'foo-{{.Arch}}-{{.OS}}.tar.gz'
  description: Count your code, quickly
```

Then you can use this registry.

```yaml
registries:
- name: foo
  type: github_content
  repo_owner: suzuki-shunsuke
  repo_name: foo
  ref: v1.0.0 # renovate: depName=suzuki-shunsuke/foo
  path: aqua-registry.yaml

packages:
- name: suzuki-shunsuke/foo@v1.0.0
  registry: foo
```

But it is bothersome to write `registries` definition per package, and users can't search packages from standard registry by `aqua g`.

## How to solve

Let's introduce the special registry `package`.

```yaml
packages:
- name: suzuki-shunsuke/foo@v1.0.0
  registry: package
```

`package` is a short syntax of `github_content` package.

```yaml
registries:
- name: foo
  type: github_content
  repo_owner: suzuki-shunsuke
  repo_name: foo
  ref: v1.0.0 # renovate: depName=suzuki-shunsuke/foo
  path: aqua-registry.yaml
```
