### ISSUE TITLE
Skip installing in unsupported platform

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#438]
## Problem to solve

Some packages are supported restricted platform.
For example, [containerd/nerdctl](https://github.com/containerd/nerdctl) doesn't support macOS.
So on macOS it is good to skip installing `containerd/nerdctl`.

## How to solve

Add the filed such as `if` to Registry Configuration.

registry.yaml

AS IS

```yaml
- type: github_release
  repo_owner: containerd
  repo_name: nerdctl
  asset: 'nerdctl-{{trimV .Version}}-{{.OS}}-{{.Arch}}.tar.gz'
  replacements:
    darwin: linux # nerdctl doesn't support macOS
```

TO BE

```yaml
- type: github_release
  repo_owner: containerd
  repo_name: nerdctl
  asset: 'nerdctl-{{trimV .Version}}-{{.OS}}-{{.Arch}}.tar.gz'
  if: GOOS != "darwin"
```

If `if` isn't set, the package is always installed.

## Consideration: Warning

It is noisy that the warning is outputted every time.
It is good to output the debug log.

## Reference

* https://aquaproj.github.io/docs/reference/registry-config
* https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md
