### ISSUE TITLE
Support Rosetta 2 more simply

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#442]
## Type

Registry Configuration

## Problem to solve

To support M1 Mac, you have to write a little complicated configuraiton.

For example, please see `assets` and `files[].src`.

https://github.com/aquaproj/aqua-registry/blob/8435092a35823ddca96fe85f5a415a672fb69971/registry.yaml#L195-L203

```yaml
- type: github_release
  repo_owner: argoproj
  repo_name: argo-workflows
  asset: 'argo-{{.OS}}-{{if eq .GOOS "darwin"}}amd64{{else}}{{.Arch}}{{end}}.gz'
  link: https://argoproj.github.io/argo-workflows/
  description: 'Argo Worfkflows CLI. Workflow engine for Kubernetes'
  files:
  - name: argo
    src: 'argo-{{.OS}}-{{if eq .GOOS "darwin"}}amd64{{else}}{{.Arch}}{{end}}'
```

### 1. Add a template function

I want to add a template function.

e.g.

```yaml
asset: 'argo-{{.OS}}-{{ArchM1}}.gz'
```

### 2. Add `rosetta2` field

```yaml
rosetta2: true
```
