### ISSUE TITLE
The output of `aqua g kubernetes-sigs/kustomize` is wrong

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#492]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 0.8.10 (e8defdfa808432aa2e186d6306c355fdf2f8dc54)
```

## Environment

:warning: aqua doesn't support Windows.

* OS (Linux, macOS, etc): `macOS`
* CPU Architecture (amd64, arm64, etc): `amd64`

Environment has nothing to do with this issue.

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

```yaml
# aqua.yaml
registries:
- type: standard
  ref: v0.12.3
```

```console
$ aqua g kubernetes-sigs/kustomize
- name: kubernetes-sigs/kustomize@kyaml/v0.13.1
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ 
```

## Expected Behaviour

```console
$ aqua g kubernetes-sigs/kustomize
- name: kubernetes-sigs/kustomize@kustomize/v4.4.1
```

## Actual Behaviour

```console
$ aqua g kubernetes-sigs/kustomize
- name: kubernetes-sigs/kustomize@kyaml/v0.13.1
```

## References

* https://github.com/kubernetes-sigs/kustomize/releases

**Comment by suzuki-shunsuke** [comment]
Support filtering tags in `aqua g`.
Add the attribute to Registry Configuration. 
https://aquaproj.github.io/docs/reference/registry-config

**Comment by suzuki-shunsuke** [comment]
Fix to get the list of releases and filter them.
https://github.com/aquaproj/aqua/blob/14e6daf2789678328de0be4af6ed2c8836fb4bd0/pkg/controller/generate.go#L175

**Comment by suzuki-shunsuke** [comment]
Add `tag_condition`.

```yaml
- type: github_release
  repo_owner: kubernetes-sigs
  repo_name: kustomize
  asset: 'kustomize_{{trimPrefix "kustomize/" .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
  tag_condition: 'Version startsWith "kustomize/"'
  version_constraint: 'semverWithVersion(">= 4.2.0", trimPrefix(Version, "kustomize/"))'
  version_overrides:
  - version_constraint: 'semverWithVersion("< 4.2.0", trimPrefix(Version, "kustomize/"))'
    rosetta2: true
```

**Comment by suzuki-shunsuke** [comment]
Add `version_source`.

```yaml
- type: github_release
  repo_owner: kubernetes-sigs
  repo_name: kustomize
  asset: 'kustomize_{{trimPrefix "kustomize/" .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
  version_source:
    filter: 'Version startsWith "kustomize/"'
  version_constraint: 'semverWithVersion(">= 4.2.0", trimPrefix(Version, "kustomize/"))'
  version_overrides:
  - version_constraint: 'semverWithVersion("< 4.2.0", trimPrefix(Version, "kustomize/"))'
    rosetta2: true
```
