### ISSUE TITLE
Remove `inline` Registry

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#520]
## Feature Overview

Remove `inline` Registry.

## Why is the feature needed?

> Please explain the problem you want to solve.

To make aqua simple.
`inline` Registry can be replaced with `local` Registry.
We can remove code and bug about `inline` Registry.

## Does the feature include Breaking Changes?

Yes

### How tomigrate

Use `local` Registry instead of `inline` Registry.

https://aquaproj.github.io/docs/reference/config

AS IS

aqua.yaml

```yaml
inline_registry:
  packages:
  - type: github_release
    repo_owner: suzuki-shunsuke
    repo_name: cmdx
    asset: 'cmdx_{{trimV .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
```

TO BE

aqua.yaml

```yaml
registries:
- name: inline
  type: local
  path: registry.yaml
```

registry.yaml

```yaml
packages:
- type: github_release
  repo_owner: suzuki-shunsuke
  repo_name: cmdx
  asset: 'cmdx_{{trimV .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
```

## Example Code

> command and configuration

```console
$ 
```

```yaml

```
