### ISSUE TITLE
Support defining custom templates in Registry Configuration

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#540]
## Feature Overview

Support defining custom templates in Registry Configuration.

[github-comment](https://github.com/suzuki-shunsuke/github-comment) and [tfcmt](https://github.com/suzuki-shunsuke/tfcmt) support the similar feature.

e.g. registry.yaml

```yaml
templates:
- name: aarch64
  template: '{{if and (eq .GOOS "linux") (eq .GOARCH "arm64")}}aarch64{{else}}{{.Arch}}{{end}}'
packages:
- type: github_release
  repo_owner: abiosoft
  repo_name: colima
  asset: 'colima-{{.OS}}-{{template "aarch64" .}}'
```

## Why is the feature needed?

> Please explain the problem you want to solve.

It is useful to refactor Registry Configuration.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ 
```

```yaml

```
