### ISSUE TITLE
`aqua i` raises a panic with invalid Registry Configuration (`github_release` package doesn't have `asset`)

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#551]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 0.10.1 (eb72cac18adab123382c0983ce5a449292c543f6)
```

## Environment

:warning: aqua doesn't support Windows.

* OS (Linux, macOS, etc): macOS
* CPU Architecture (amd64, arm64, etc): arm64

## Overview

`aqua i` raises a panic.

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

```yaml
# aqua.yaml
registries:
- name: standard
  type: local
  path: registry.yaml

packages:
- name: anchore/syft@v0.36.0
```

```yaml
- type: github_release
  repo_owner: anchore
  repo_name: syft
  format: tar.gz
  format_overrides:
  - goos: darwin
    format: zip
  - goos: windows
    format: zip
  version_constraint: 'semver("!= 0.36.0")'
  version_overrides:
  - version_constraint: 'semver("= 0.36.0")'
    replacements:
      windows: Windows
      amd64: x86_64
```

```console
$ aqua i
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104ce3570]

goroutine 37 [running]:
github.com/aquaproj/aqua/pkg/controller.(*Template).Parse(0x0)
	/home/runner/work/aqua/aqua/pkg/controller/template.go:41 +0x20
github.com/aquaproj/aqua/pkg/controller.(*Template).Execute(0x0, {0x104e8ca60, 0x140005203f0})
	/home/runner/work/aqua/aqua/pkg/controller/template.go:53 +0x28
github.com/aquaproj/aqua/pkg/controller.(*PackageInfo).RenderAsset(0x140003dd300, 0x14000036140)
	/home/runner/work/aqua/aqua/pkg/controller/package_info.go:212 +0xaf8
github.com/aquaproj/aqua/pkg/controller.(*Controller).installPackage(0x140004852c0, {0x104f81c60, 0x1400043f780}, 0x140003dd300, 0x14000036140, 0x0)
	/home/runner/work/aqua/aqua/pkg/controller/install_packages.go:195 +0x270
github.com/aquaproj/aqua/pkg/controller.(*Controller).installPackages.func2(0x140007aef60, 0x14000033620, 0x140004852c0, 0x14000544000, 0x140004b6750, 0x1400079cc30, {0x104f81c60, 0x1400043f780}, 0x0, 0x14000036140)
	/home/runner/work/aqua/aqua/pkg/controller/install_packages.go:120 +0x464
created by github.com/aquaproj/aqua/pkg/controller.(*Controller).installPackages
	/home/runner/work/aqua/aqua/pkg/controller/install_packages.go:81 +0xa9c
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ 
```

## Expected Behaviour

panic doesn't occur.

## Actual Behaviour

panic occurs.

## References

* https://github.com/aquaproj/aqua-registry/pull/1864
* https://github.com/hashicorp/go-version
* https://aquaproj.github.io/docs/reference/registry-config
