### ISSUE TITLE
`aqua g -i` ignores the indent of `registries` when `packages:` is empty

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#585]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 1.1.0-1 (29095a314be902a216d0eec145cd0e3c0dc08e1f)
```

## Environment

:warning: aqua doesn't support Windows.

* OS (Linux, macOS, etc): macOS
* CPU Architecture (amd64, arm64, etc): arm64

I guess OS and architecture aren't related.

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

aqua.yaml

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v1.4.0 # renovate: depName=aquaproj/aqua-registry
packages:
```

```console
$ aqua g -i cli/cli
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ 
```

## Expected Behaviour

The indent of `packages` is same as `registries`.

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v1.4.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: cli/cli@v2.5.1
```

## Actual Behaviour

The indent of `packages` isn't same as `registries`.

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v1.4.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.5.1
```

## Important Factoids

[goccy/go-yaml](https://github.com/goccy/go-yaml) is used as YAML Parser.

## References

* https://pkg.go.dev/github.com/goccy/go-yaml@v1.9.5
