### ISSUE TITLE
[Feature Request] Add `replacements_overrides` param for registry

### ISSUE THREAD

**Issue by 4513ECHO** [aquaproj/aqua#607]
## Feature Overview

Add `replacements_overrides` param for registry to make registry more declarative.

## Why is the feature needed?

> Please explain the problem you want to solve.

Some packages written in rust have a little strange pattern for asset.
We can use `{{if eq .VARIABLE}}~~{{else}}~~{{end}}` for such pattern, but it is complicated.
Why don't we add `replacements_overrides` like `format_overrides` or `rosetta2`?
It makes registry more declarative.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```yaml
- type: github_release
  repo_owner: sharkdp
  repo_name: bat
  rosetta2: true
  asset: 'bat-{{.Version}}-{{.Arch}}-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}unknown-linux-musl{{else}}unknown-linux-gnu{{end}}{{else}}{{.OS}}{{end}}.{{.Format}}'
  description: 'A cat(1) clone with wings.'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    amd64: x86_64
    arm64: aarch64
    darwin: apple-darwin
    windows: pc-windows-msvc
    386: i686
  files:
  - name: bat
    src: 'bat-{{.Version}}-{{.Arch}}-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}unknown-linux-musl{{else}}unknown-linux-gnu{{end}}{{else}}{{.OS}}{{end}}/bat'
```

to

```diff
 - type: github_release
  repo_owner: sharkdp
  repo_name: bat
  rosetta2: true
- asset: 'bat-{{.Version}}-{{.Arch}}-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}unknown-linux-musl{{else}}unknown-linux-gnu{{end}}{{else}}{{.OS}}{{end}}.{{.Format}}'
+ asset: 'bat-{{.Version}}-{{.Arch}}-{{.OS}}.{{.Format}}'
  description: 'A cat(1) clone with wings.'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    amd64: x86_64
    arm64: aarch64
    darwin: apple-darwin
+   linux: unknown-linux-musl
    windows: pc-windows-msvc
    386: i686
+ replacements_overrides:
+ - goos: linux
+   goarch: arm64
+   replacements:
+     linux: unknown-linux-gnu
  files:
  - name: bat
    src: 'bat-{{.Version}}-{{.Arch}}-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}unknown-linux-musl{{else}}unknown-linux-gnu{{end}}{{else}}{{.OS}}{{end}}/bat'
```

**Comment by suzuki-shunsuke** [comment]
Sorry for late reply.
And thank you for your proposal.
I've also been feeling the same issue and I've considered some solutions.

`replacements_overrides` looks simple and good.
I'd like to verify this approach.

**Comment by suzuki-shunsuke** [comment]
Other options

* https://github.com/aquaproj/aqua/issues/540
* Supports template in `replacements`

**Comment by suzuki-shunsuke** [comment]
> A similar alternative could be to allow for OS+arch in replacements:

It's interesting.

**Comment by 4513ECHO** [comment]
It will reduce not only for `linux-arm64`, but also other `{{if eq ~ }}`. How many `{{if eq ~ }}` are there in registry?

**Comment by 4513ECHO** [comment]
> It's fewer than I expected.

Perhaps I think tools which are not fixed for `linux-arm64` exist.

**Comment by suzuki-shunsuke** [comment]
```console
$ grep '{{if' registry.yaml | wc -l
      39
```

<details>

```
$ grep '{{if' registry.yaml 
  asset: 'colima-{{.OS}}-{{if and (eq .GOOS "linux") (eq .GOARCH "arm64")}}aarch64{{else}}{{.Arch}}{{end}}'
  asset: 'arkade{{if eq .GOOS "darwin"}}-darwin{{else}}{{if ne .GOARCH "amd64"}}-{{.Arch}}{{end}}{{end}}'
  asset: 'k3sup{{if eq .GOOS "darwin"}}-darwin{{else}}{{if ne .GOARCH "amd64"}}-{{.Arch}}{{end}}{{end}}'
  asset: 'btop-{{if and (eq .GOOS "linux") (eq .GOARCH "arm64")}}aarch64{{else}}{{.Arch}}{{end}}-{{.OS}}.tbz'
  asset: 'pack-{{.Version}}-{{.OS}}{{if and (eq .GOOS "darwin") (eq .GOARCH "arm64")}}-{{.Arch}}{{end}}.tgz'
    src: 'gh_{{trimV .Version}}_{{.OS}}_{{if eq .GOOS "darwin"}}amd64{{else}}{{.Arch}}{{end}}/bin/gh'
  asset: 'cloudflared-{{.OS}}-{{.Arch}}{{if eq .GOOS "darwin"}}.tgz{{end}}'
  asset: 'ddosify_{{trimV .Version}}_{{title .OS}}_{{if eq .GOOS "darwin"}}all{{else}}{{.Arch}}{{end}}.{{.Format}}'
  url: 'https://downloads.dockerslim.com/releases/{{.Version}}/dist_{{.OS}}{{if ne .Arch "amd64"}}_{{if eq .GOOS "darwin"}}m1{{else}}{{.Arch}}{{end}}{{end}}.{{.Format}}'
    src: 'dist_{{.OS}}{{if ne .Arch "amd64"}}_{{if eq .GOOS "darwin"}}m1{{else}}{{.Arch}}{{end}}{{end}}/docker-slim'
    src: 'dist_{{.OS}}{{if ne .Arch "amd64"}}_{{if eq .GOOS "darwin"}}m1{{else}}{{.Arch}}{{end}}{{end}}/docker-slim-sensor'
  asset: 'dotenv-linter-{{.OS}}-{{if and (eq .GOOS "darwin") (eq .GOARCH "arm64")}}arm64{{else}}{{if and (eq .GOOS "windows") (eq .GOARCH "amd64")}}x64{{else}}{{.Arch}}{{end}}{{end}}.{{.Format}}'
    src: '{{.OS}}-{{if eq .GOOS "darwin"}}amd64{{else}}{{.Arch}}{{end}}/gofish'
  asset: 'iam-policy-json-to-terraform{{if eq .OS "darwin"}}_darwin{{else}}_amd64{{end}}'
    src: 'gost-{{.OS}}-{{if eq .GOOS "darwin"}}amd64{{else}}{{.Arch}}{{end}}-{{trimV .Version}}'
    src: 'hub-{{.OS}}-{{if eq .GOOS "darwin"}}amd64{{else}}{{.Arch}}{{end}}-{{trimV .Version}}/bin/hub'
  asset: 'gleam-{{.Version}}-{{.OS}}{{if or (ne .GOOS "darwin") (ne .GOARCH "amd64")}}-{{.Arch}}{{end}}.{{.Format}}'
    src: 'container-structure-test-{{.OS}}-{{if eq .GOOS "darwin"}}amd64{{else}}{{.Arch}}{{end}}'
  asset: 'goreleaser_{{title .OS}}_{{if eq .GOOS "darwin"}}all{{else}}{{.Arch}}{{end}}.tar.gz'
  asset: 'jump_{{.OS}}{{if eq .OS "linux"}}_{{.Arch}}_binary{{end}}'
  asset: 'inlets-pro{{if eq .OS "darwin"}}-darwin{{end}}{{if eq .GOARCH "arm64"}}-arm64{{end}}'
  asset: 'inletsctl{{if eq .GOOS "darwin"}}-darwin{{else}}{{if eq .GOARCH "arm64"}}-arm64{{end}}{{end}}.tgz'
    src: 'inletsctl{{if eq .GOOS "darwin"}}-darwin{{else}}{{if eq .GOARCH "arm64"}}-arm64{{end}}{{end}}'
  asset: 'istioctl-{{.Version}}-{{.OS}}{{if ne .GOOS "darwin"}}-{{.Arch}}{{end}}.tar.gz'
  asset: 'deck_{{trimV .Version}}_{{.OS}}_{{if eq .GOOS "darwin"}}all{{else}}{{.Arch}}{{end}}.tar.gz'
  asset: 'lima-{{trimV .Version}}-{{title .OS}}-{{if and (eq .GOOS "linux") (eq .GOARCH "arm64")}}aarch64{{else}}{{.Arch}}{{end}}.tar.gz'
    src: '{{if eq .GOOS "linux"}}mongocli_{{trimV .Version}}_{{.OS}}_{{.Arch}}/{{end}}bin/mongocli'
    src: 'nvim-{{if eq .GOOS "darwin"}}osx64{{else}}{{.OS}}{{end}}/bin/nvim'
  asset: 'faas-cli{{if eq .GOOS "darwin"}}-darwin{{else}}{{if ne .GOARCH "amd64"}}{{.Arch}}{{end}}{{end}}'
  asset: 'kots_{{.OS}}_{{if eq .GOOS "darwin"}}all{{else}}{{.Arch}}{{end}}.tar.gz'
  asset: 'kfilt_{{trimV .Version}}_{{.OS}}_{{if eq .GOOS "darwin"}}all{{else}}{{.Arch}}{{end}}'
  asset: 'fnm-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}linux{{else}}{{.Arch}}{{end}}{{else}}{{.OS}}{{end}}.zip'
  asset: 'yj-{{.OS}}{{if and (eq .GOOS "linux") (ne .GOARCH "amd64")}}-{{.Arch}}{{end}}'
  asset: 'bat-{{.Version}}-{{.Arch}}-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}unknown-linux-musl{{else}}unknown-linux-gnu{{end}}{{else}}{{.OS}}{{end}}.{{.Format}}'
    src: 'bat-{{.Version}}-{{.Arch}}-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}unknown-linux-musl{{else}}unknown-linux-gnu{{end}}{{else}}{{.OS}}{{end}}/bat'
  asset: 'fd-{{.Version}}-{{.Arch}}-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}unknown-linux-musl{{else}}unknown-linux-gnu{{end}}{{else}}{{.OS}}{{end}}.{{.Format}}'
    src: 'fd-{{.Version}}-{{.Arch}}-{{if eq .GOOS "linux"}}{{if eq .GOARCH "amd64"}}unknown-linux-musl{{else}}unknown-linux-gnu{{end}}{{else}}{{.OS}}{{end}}/fd'
  asset: 'nebula-{{.OS}}{{if ne .GOOS "darwin"}}-{{.Arch}}{{end}}.{{.Format}}'
  asset: 'websocat_{{if eq .GOOS "darwin"}}mac{{else}}linux64{{end}}'
```

</details>

**Comment by suzuki-shunsuke** [comment]
It looks good.

AS IS

```yaml
  asset: 'colima-{{.OS}}-{{if and (eq .GOOS "linux") (eq .GOARCH "arm64")}}aarch64{{else}}{{.Arch}}{{end}}'
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
```

TO BE

```yaml
  asset: 'colima-{{.OS}}-{{.Arch}}'
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
  replacements_overrides:
  - goos: linux
    goarch: arm64
    replacements:
      arm64: aarch64
```

**Comment by suzuki-shunsuke** [comment]
`application specific DSL` or `standard template language (Go's text/template)`

**Comment by suzuki-shunsuke** [comment]
I've implemented `replacements_overrides`.
I'll test this and verify if this should be merged.
https://github.com/aquaproj/aqua/pull/617

**Comment by suzuki-shunsuke** [comment]
Using `replacements_overrides` you can refactor some packages.

https://github.com/aquaproj/aqua-registry/pull/2696/files

But there are still packages which you can't refactor with `replacements_overrides`.

e.g. https://github.com/aquaproj/aqua-registry/blob/c3d1180c74cb655b86d31ea8ccdd1e9a09133cad/registry.yaml#L149

**Comment by suzuki-shunsuke** [comment]
Maybe `asset_overrides` is needed.

AS IS

```yaml
asset: 'arkade{{if eq .GOOS "darwin"}}-darwin{{else}}{{if ne .GOARCH "amd64"}}-{{.Arch}}{{end}}{{end}}'
```

TO BE

```yaml
  asset: arkade
  asset_overrides:
  - goos: linux
    goarch: arm64
    asset: 'arkade-{{.Arch}}'
  - goos: darwin
    goarch: amd64
    asset: 'arkade-darwin'
  - goos: darwin
    asset: 'arkade-darwin-{{.Arch}}'
```

**Comment by suzuki-shunsuke** [comment]
Hmm...
You have to fix file's src too.

https://github.com/aquaproj/aqua-registry/blob/c3d1180c74cb655b86d31ea8ccdd1e9a09133cad/registry.yaml#L1957-L1961

```yaml
  asset: 'inletsctl{{if eq .GOOS "darwin"}}-darwin{{else}}{{if eq .GOARCH "arm64"}}-arm64{{end}}{{end}}.tgz'
  files:
  - name: inletsctl
    src: 'inletsctl{{if eq .GOOS "darwin"}}-darwin{{else}}{{if eq .GOARCH "arm64"}}-arm64{{end}}{{end}}'
```

**Comment by suzuki-shunsuke** [comment]
# Idea: Add `overrides`

```yaml
- type: github_release
  repo_owner: inlets
  repo_name: inletsctl
  description: Create inlets servers on the top cloud platforms
  asset: inletsctl.tgz
  overrides:
  - goos: darwin
    asset: 'inletsctl-darwin.tgz'
    files:
    - name: inletsctl
      src: inletsctl-darwin
  - goarch: arm64
    asset: 'inletsctl-arm64.tgz'
    files:
    - name: inletsctl
      src: inletsctl-arm64
```
