### ISSUE TITLE
Support package aliases

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#674]
## Feature Overview

Support defining aliases of package names.
You can install, execute, and search packages with aliases.
~If aliases are used in `aqua.yaml`, aqua warns to encourage the primary package name.~

## Why is the feature needed?

> Please explain the problem you want to solve.

Sometimes repositories of packages are changed.
For example, talos-systems was renamed to siderolabs. https://github.com/aquaproj/aqua-registry/pull/3224
And `ahmetb/kubens` was deprecated. https://github.com/aquaproj/aqua-registry/pull/1691

For compatibility, we would like to support package aliases and allows old package names.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ 
```

registry.yaml

```yaml
packages:
  - name: ahmetb/kubectx/kubens
    type: github_release
    repo_owner: ahmetb
    repo_name: kubectx
    aliases:
      - name: ahmetb/kubens
```
