### ISSUE TITLE
[Bug Report] Install failed when release is executable file

### ISSUE THREAD

**Issue by 4513ECHO** [aquaproj/aqua#683]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 1.5.0 (9d1d73bb167f8cd791e7082852f75dedeb1d9b3d)
```

## Environment

:warning: aqua doesn't support Windows.

* OS (Linux, macOS, etc):

`linux (Ubuntu)`

* CPU Architecture (amd64, arm64, etc):

`arm64 (Raspberry Pi)`

## Overview

Auqa failed when relase is single executable file.
For example, I added [`antonmedv/fx`](https://github.com/antonmedv/fx) to registry.
[Its release](https://github.com/antonmedv/fx/releases/tag/22.0.10) contains only executable files.

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

```yaml
# aqua.yaml
---
registries:
  - name: local
    type: local
    path: experimental.yaml

packages:
  - name: antonmedv/fx@22.0.10
    registry: local
```

```yaml
# experimental.yaml
---
packages:
  # init: a
  - type: github_release
    repo_owner: antonmedv
    repo_name: fx
    asset: 'fx_{{.OS}}_{{.Arch}}'
    description: Terminal JSON viewer
    files:
      - name: fx
        src: 'fx_{{.OS}}_{{.Arch}}'
```

```console
$ AQUA_CONFIG=./aqua.yaml aqua i --test
ERRO[0000] install the package                           aqua_version=1.5.0 error="check file_src is correct: exe_path isn't found: stat /home/hibiki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/antonmedv/fx/22.0.10/fx_linux_arm64/fx_linux_arm64: no such file or directory" file_name=fx package_name=antonmedv/fx package_version=22.0.10 program=aqua registry=local
FATA[0000] aqua failed                                   aqua_version=1.5.0 error="it failed to install some packages" program=aqua
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ AQUA_CONFIG=./aqua.yaml AQUA_LOG_LEVEL=debug aqua i --test
DEBU[0000] install the proxy                             aqua_version=1.5.0 package_name=aqua-proxy package_version=v1.0.0 program=aqua registry=
DEBU[0000] check if aqua-proxy is already installed      aqua_version=1.5.0 package_name=aqua-proxy package_version=v1.0.0 program=aqua registry=
DEBU[0000] install the package                           aqua_version=1.5.0 package_name=antonmedv/fx package_version=22.0.10 program=aqua registry=local
DEBU[0000] check if the package is already installed     aqua_version=1.5.0 package_name=antonmedv/fx package_version=22.0.10 program=aqua registry=local
ERRO[0000] install the package                           aqua_version=1.5.0 error="check file_src is correct: exe_path isn't found: stat /home/hibiki/.local/share/aquaproj-aqua/pkgs/github_release/github.com/antonmedv/fx/22.0.10/fx_linux_arm64/fx_linux_arm64: no such file or directory" file_name=fx package_name=antonmedv/fx package_version=22.0.10 program=aqua registry=local
FATA[0000] aqua failed                                   aqua_version=1.5.0 error="it failed to install some packages" program=aqua
```

## Expected Behaviour

Aqua should be success to install

## Actual Behaviour

Aqua failed.

## Important Factoids

I tried to remove `files` property, but it also failed.

## References

*

**Comment by suzuki-shunsuke** [comment]
Thank you for you report.

antonmedv/fx has already been included in aqua-registry.
https://github.com/aquaproj/aqua-registry/blob/v2.11.1/registry.yaml#L692-L706

And in macOS arm64, it works well.

```console
$ aqua -v     
aqua version 1.5.0 (9d1d73bb167f8cd791e7082852f75dedeb1d9b3d)
```

aqua.yaml

```yaml
registries:
- type: standard
  ref: v2.11.1
packages:
- name: antonmedv/fx@22.0.10
```

macOS arm64

```console
$ aqua i
INFO[0000] download and unarchive the package            aqua_version=1.5.0 package_name=antonmedv/fx package_version=22.0.10 program=aqua registry=standard registry_ref=v2.11.1

$ fx --version
22.0.10
```
