### ISSUE TITLE
Support extracting required packages from standard registry and generate local registry to improve performance

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#685]
## Feature Overview

Support extracting required packages from standard registry and generate local registry to improve performance.

## Why is the feature needed?

> Please explain the problem you want to solve.

aqua reads huge YAML files, standard registry.
It takes a little long time and affects the performance of aqua.
If the number of packages in aqua-registry will become 100x, it may be hard to use aqua due to the performance.
This is the aqua's architecture issue regarding to the performance.

To solve the issue, I consider to generate local registry extracting required packages from standard registry.

## Does the feature include Breaking Changes?

Probably No.

## Example Code

> command and configuration

```yaml
registries:
- type: standard
  ref: v2.11.1 # renovate: depName=aquaproj/aqua-registry
  local_path: aqua-registry.json
packages:
- name: rhysd/actionlint@v1.6.12
```

```console
$ aqua build-registry # Generate aqua-registry.json
```

## Concerns

This feature improves the performance of aqua, but on the other hand the learning cost of aqua becomes larger.
We don't want to add new commands as much as possible.
And currently, aqua doesn't have a performance issue, so maybe we don't have to improve the performance by adding new features.
