### ISSUE TITLE
Support test command

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#72]
```yaml
- name: tfmigrate
  type: github_release
  repo_owner: minamijoyo
  repo_name: tfmigrate
  artifact: 'tfmigrate_{{trimPrefix "v" .Package.Version}}_{{.OS}}_{{.Arch}}.tar.gz'
  files:
  - name: tfmigrate
  test:
    args: ["-v"]
    quiet: true
```

After installing the package the test command is executed and the exit code is checked.

```
tfmigrate -v
```
