### ISSUE TITLE
Support building Go tool to install

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#798]
## Feature Overview

Support build Go tools to install them.

## Why is the feature needed?

> Please explain the problem you want to solve.

To support Go tools that assets aren't provided officially.

## Does the feature include Breaking Changes?

No.

## Example Code

> command and configuration

```console
$ aqua i
```

registry.yaml

https://github.com/mitchellh/gox

```yaml
packages:
  - type: go
    repo_owner: mitchellh
    repo_name: gox
    description: A dead simple, no frills Go cross compile tool
    # By default, `go build -o <build path> .` is run
```

```
$AQUA_ROOT/
  pkgs/
    go/
      github.com/mitchellh/gox/v1.0.1/
        src/
        bin/
          gox
```
