### ISSUE TITLE
install multiple binaries from one registry

### ISSUE THREAD

**Issue by Pranc1ngPegasus** [aquaproj/aqua#866]
## Feature Overview
I am using [fzf-tmux](https://github.com/junegunn/fzf/blob/master/bin/fzf-tmux) within `junegunn/fzf`.
I was installed fzf with following description, but `fzf-tmux` was not installed.
Off course my `~/.local/share/aquaproj-aqua/bin/` directory doesn't have fzf-tmux binary.

## Why is the feature needed?

> Please explain the problem you want to solve.

I want you to install multiple binaries from one registry, or divide to registries for install multiple binaries like fzf-tmux.

## Does the feature include Breaking Changes?

I don't think so.

## Example Code

> command and configuration

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v2.22.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: junegunn/fzf@0.30.0
```
