### ISSUE TITLE
Add `supported_envs` instead of `supported_if`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#882]
## Feature Overview

Add a field `supported_envs` instead of `supported_if`.
You can specify the list of supported environments (GOOS and GOARCH) in `supported_envs`.

## Why is the feature needed?

> Please explain the problem you want to solve.

`supported_if` has two problems.

1. Complicated. There are multiple ways to express the same environments. The expression is too flexible 
1. Performance. aqua has to compile and evaluate the expression per tool. It may affect the performance although we should do the performance test

## Does the feature include Breaking Changes?

No.

We keep supporting `supported_if`.
But when we replace the standard registry's `supported_if` to `supported_envs`, it means the breaking change.

## Example Code

> command and configuration

AS IS

```yaml
packages:
  - type: github_release
    repo_owner: gruntwork-io
    repo_name: terragrunt
    asset: "terragrunt_{{.OS}}_{{.Arch}}"
    supported_if: not (GOOS == "windows" and GOARCH == "arm64")
```

TO BE

```yaml
packages:
  - type: github_release
    repo_owner: gruntwork-io
    repo_name: terragrunt
    asset: "terragrunt_{{.OS}}_{{.Arch}}"
    supported_envs:
      - windows/amd64
      - darwin
      - linux
```

The following patterns are supported.

* `<GOOS>`
* `<GOOS>/<GOARCH>`
