### ISSUE TITLE
[Windows] Some tools can't be run due to `it failed to start the process`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua#883]
## aqua version

Please use the latest version.

```console
$ aqua -v
aqua version 1.12.0-0 (ccaff1e0366e41a6d6fe34ff07a325b18cf16813)
```

## Environment

:warning: aqua doesn't support Windows.

* OS (Linux, macOS, etc): windows
* CPU Architecture (amd64, arm64, etc): amd64

---

* Windows on [Amazon Workspaces](https://aws.amazon.com/workspaces/) `Standard with Windows 10 (Server 2019 based) (PCoIP)`
* Git for Windows 2.36.1
  * Git Bash
  * MINGW64

## How to reproduce

* aqua.yaml
* executed command and output

> aqua.yaml should be not partial but complete configuration.
> Please remove unneeded configuration to reproduce the issue.

```yaml
# aqua.yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v2.27.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: aquaproj/aqua-installer@v1.0.0
```

```console
$ aqua-installer
time="2022-06-18T10:15:37+09:00" level=fatal msg="aqua failed" aqua_version=1.12.0-0 env=windows/amd64 error="it failed to start the process" program=aqua
```

## Debug Output

Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.

```console
$ 
```

## Expected Behaviour

The command is run successfully.

## Actual Behaviour

If failed to run the command due to `it failed to start the process`.

## References

* https://github.com/aquaproj/aqua/issues/850#issuecomment-1155982542
