### ISSUE TITLE
How to switch if multiple pkgs provide commands with the same name?

### ISSUE THREAD

**Issue by tadayosi** [aquaproj/aqua#899]
What should I do to resolve the conflict if multiple pkgs provide commands with the same name?

For example, `apache/camel-k` provides `kamel` command, but sometimes I want to use the same `kamel` command provided from a commercial vendor. I can create a local registry for the pkg from the vendor. However, if putting the two pkgs in the same `aqua.yaml`, it seems that the first one in the pkg list always takes precedence over the second one.

Is reordering the pkgs in the list of `aqua.yaml` the only/right way to switch the command between the pkgs?

**Comment by suzuki-shunsuke** [comment]
> Is reordering the pkgs in the list of aqua.yaml the only/right way to switch the command between the pkgs?

I think so.
In the other way, you can also switch multiple aqua.yaml with the environment variable `AQUA_CONFIG` or `-c` option.

e.g.

```console
$ AQUA_CONFIG=aqua-2.yaml kamel --help
```

```console
$ aqua -c aqua-2.yaml exec -- kamel --help
```

**Comment by suzuki-shunsuke** [comment]
Alternatively, you can rename the tool version with the local registry.

e.g.

```yaml
packages:
  - type: github_release
    repo_owner: apache # Change the repository to commercial vendor
    repo_name: camel-k # Change the repository to commercial vendor
    asset: "camel-k-client-{{trimV .Version}}-{{.OS}}-{{.Arch}}.tar.gz"
    description: Apache Camel K is a lightweight integration platform, born on Kubernetes, with serverless superpowers
    supported_if: GOOS == "darwin" or GOARCH == "amd64"
    files:
      - name: kamel-commercial-vendor # Rename
        src: kamel
    replacements:
      amd64: 64bit
      arm64: arm64bit
      darwin: mac
```
